In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set_style('whitegrid')
pd.pandas.set_option('display.max_columns', None)

In [2]:
train = pd.read_csv('../input/home-credit-default-risk/application_train.csv')
test = pd.read_csv('../input/home-credit-default-risk/application_test.csv')

In [3]:
train['TARGET'].value_counts()

0    282686
1     24825
Name: TARGET, dtype: int64

In [4]:
categorical_features = train.select_dtypes('object')

In [5]:
miss_val = train.isnull().sum()
miss_val_perc = 100 * train.isnull().sum()/len(train)
miss_val_table = pd.concat([miss_val, miss_val_perc], axis = 1)
miss_val_table_rename = miss_val_table.rename(columns = {0: 'Missing Values', 1: '% of Total Values'})

In [6]:
miss_val_table_rename[miss_val_table_rename['Missing Values'] != 0].sort_values('% of Total Values', ascending = False).round(1)

                          Missing Values  % of Total Values
COMMONAREA_MEDI                   214865               69.9
COMMONAREA_AVG                    214865               69.9
COMMONAREA_MODE                   214865               69.9
NONLIVINGAPARTMENTS_MEDI          213514               69.4
NONLIVINGAPARTMENTS_MODE          213514               69.4
...                                  ...                ...
EXT_SOURCE_2                         660                0.2
AMT_GOODS_PRICE                      278                0.1
AMT_ANNUITY                           12                0.0
CNT_FAM_MEMBERS                        2                0.0
DAYS_LAST_PHONE_CHANGE                 1                0.0

[67 rows x 2 columns]

In [7]:
def missing(df):
    miss_val = df.isnull().sum()
    miss_val_perc = 100 * df.isnull().sum()/len(df)
    miss_val_table = pd.concat([miss_val, miss_val_perc], axis = 1)
    miss_val_table_rename = miss_val_table.rename(columns = {0: 'Missing Values', 1: '% of Total Values'})
    miss = miss_val_table_rename[miss_val_table_rename['Missing Values'] != 0].sort_values('% of Total Values', ascending = False).round(1)
    print("Your dataframe has "+ str(df.shape[1]) + " columns out of which " + str(miss.shape[0]) + " columns have missing values.")
    return miss

In [8]:
missing(train)

Your dataframe has 122 columns out of which 67 columns have missing values.

                          Missing Values  % of Total Values
COMMONAREA_MEDI                   214865               69.9
COMMONAREA_AVG                    214865               69.9
COMMONAREA_MODE                   214865               69.9
NONLIVINGAPARTMENTS_MEDI          213514               69.4
NONLIVINGAPARTMENTS_MODE          213514               69.4
...                                  ...                ...
EXT_SOURCE_2                         660                0.2
AMT_GOODS_PRICE                      278                0.1
AMT_ANNUITY                           12                0.0
CNT_FAM_MEMBERS                        2                0.0
DAYS_LAST_PHONE_CHANGE                 1                0.0

[67 rows x 2 columns]

In [9]:
train.dtypes.value_counts()

float64    65
int64      41
object     16
dtype: int64

In [10]:
categorical_features.apply(pd.Series.nunique, axis = 0)

NAME_CONTRACT_TYPE             2
CODE_GENDER                    3
FLAG_OWN_CAR                   2
FLAG_OWN_REALTY                2
NAME_TYPE_SUITE                7
NAME_INCOME_TYPE               8
NAME_EDUCATION_TYPE            5
NAME_FAMILY_STATUS             6
NAME_HOUSING_TYPE              6
OCCUPATION_TYPE               18
WEEKDAY_APPR_PROCESS_START     7
ORGANIZATION_TYPE             58
FONDKAPREMONT_MODE             4
HOUSETYPE_MODE                 3
WALLSMATERIAL_MODE             7
EMERGENCYSTATE_MODE            2
dtype: int64

In [64]:
bureau = pd.read_csv('../input/home-credit-default-risk/bureau.csv')

In [65]:
previous_loan_accounts = bureau.groupby('SK_ID_CURR', as_index = False)['SK_ID_BUREAU'].count().rename(columns = {"SK_ID_BUREAU": "PREVIOUS_LOAN_ACCOUNTS"})

In [66]:
temp = train.merge(previous_loan_accounts, on = 'SK_ID_CURR', how = 'left')

In [67]:
temp['PREVIOUS_LOAN_ACCOUNTS'].isnull().sum()

44020

In [68]:
temp['PREVIOUS_LOAN_ACCOUNTS'] = temp['PREVIOUS_LOAN_ACCOUNTS'].fillna(0)

In [69]:
bureau_agg = bureau.drop('SK_ID_BUREAU', axis = 1).groupby('SK_ID_CURR', as_index = False).agg(['count','mean', 'median', 'max', 'min','sum', np.std]).reset_index()

In [70]:
columns = ['SK_ID_CURR']
for var in bureau_agg.columns.levels[0]:
    if var != 'SK_ID_CURR':
        for stat in bureau_agg.columns.levels[1][:-1]:
            columns.append('BUREAU_{}_{}'.format(var.upper(), stat.upper()))

In [71]:
bureau_agg.columns = columns

In [72]:
bureau_agg

,SK_ID_CURR,BUREAU_DAYS_CREDIT_COUNT,BUREAU_DAYS_CREDIT_MEAN,BUREAU_DAYS_CREDIT_MEDIAN,BUREAU_DAYS_CREDIT_MAX,BUREAU_DAYS_CREDIT_MIN,BUREAU_DAYS_CREDIT_SUM,BUREAU_DAYS_CREDIT_STD,BUREAU_CREDIT_DAY_OVERDUE_COUNT,BUREAU_CREDIT_DAY_OVERDUE_MEAN,BUREAU_CREDIT_DAY_OVERDUE_MEDIAN,BUREAU_CREDIT_DAY_OVERDUE_MAX,BUREAU_CREDIT_DAY_OVERDUE_MIN,BUREAU_CREDIT_DAY_OVERDUE_SUM,BUREAU_CREDIT_DAY_OVERDUE_STD,BUREAU_DAYS_CREDIT_ENDDATE_COUNT,BUREAU_DAYS_CREDIT_ENDDATE_MEAN,BUREAU_DAYS_CREDIT_ENDDATE_MEDIAN,BUREAU_DAYS_CREDIT_ENDDATE_MAX,BUREAU_DAYS_CREDIT_ENDDATE_MIN,BUREAU_DAYS_CREDIT_ENDDATE_SUM,BUREAU_DAYS_CREDIT_ENDDATE_STD,BUREAU_DAYS_ENDDATE_FACT_COUNT,BUREAU_DAYS_ENDDATE_FACT_MEAN,BUREAU_DAYS_ENDDATE_FACT_MEDIAN,BUREAU_DAYS_ENDDATE_FACT_MAX,BUREAU_DAYS_ENDDATE_FACT_MIN,BUREAU_DAYS_ENDDATE_FACT_SUM,BUREAU_DAYS_ENDDATE_FACT_STD,BUREAU_AMT_CREDIT_MAX_OVERDUE_COUNT,BUREAU_AMT_CREDIT_MAX_OVERDUE_MEAN,BUREAU_AMT_CREDIT_MAX_OVERDUE_MEDIAN,BUREAU_AMT_CREDIT_MAX_OVERDUE_MAX,BUREAU_AMT_CREDIT_MAX_OVERDUE_MIN,BUREAU_AMT_CREDIT_MAX_OVERDUE_SUM,BUREAU_AMT_CREDIT_MAX_OVERDUE_STD,BUREAU_CNT_CREDIT_PROLONG_COUNT,BUREAU_CNT_CREDIT_PROLONG_MEAN,BUREAU_CNT_CREDIT_PROLONG_MEDIAN,BUREAU_CNT_CREDIT_PROLONG_MAX,BUREAU_CNT_CREDIT_PROLONG_MIN,BUREAU_CNT_CREDIT_PROLONG_SUM,BUREAU_CNT_CREDIT_PROLONG_STD,BUREAU_AMT_CREDIT_SUM_COUNT,BUREAU_AMT_CREDIT_SUM_MEAN,BUREAU_AMT_CREDIT_SUM_MEDIAN,BUREAU_AMT_CREDIT_SUM_MAX,BUREAU_AMT_CREDIT_SUM_MIN,BUREAU_AMT_CREDIT_SUM_SUM,BUREAU_AMT_CREDIT_SUM_STD,BUREAU_AMT_CREDIT_SUM_DEBT_COUNT,BUREAU_AMT_CREDIT_SUM_DEBT_MEAN,BUREAU_AMT_CREDIT_SUM_DEBT_MEDIAN,BUREAU_AMT_CREDIT_SUM_DEBT_MAX,BUREAU_AMT_CREDIT_SUM_DEBT_MIN,BUREAU_AMT_CREDIT_SUM_DEBT_SUM,BUREAU_AMT_CREDIT_SUM_DEBT_STD,BUREAU_AMT_CREDIT_SUM_LIMIT_COUNT,BUREAU_AMT_CREDIT_SUM_LIMIT_MEAN,BUREAU_AMT_CREDIT_SUM_LIMIT_MEDIAN,BUREAU_AMT_CREDIT_SUM_LIMIT_MAX,BUREAU_AMT_CREDIT_SUM_LIMIT_MIN,BUREAU_AMT_CREDIT_SUM_LIMIT_SUM,BUREAU_AMT_CREDIT_SUM_LIMIT_STD,BUREAU_AMT_CREDIT_SUM_OVERDUE_COUNT,BUREAU_AMT_CREDIT_SUM_OVERDUE_MEAN,BUREAU_AMT_CREDIT_SUM_OVERDUE_MEDIAN,BUREAU_AMT_CREDIT_SUM_OVERDUE_MAX,BUREAU_AMT_CREDIT_SUM_OVERDUE_MIN,BUREAU_AMT_CREDIT_SUM_OVERDUE_SUM,BUREAU_AMT_CREDIT_SUM_OVERDUE_STD,BUREAU_DAYS_CREDIT_UPDATE_COUNT,BUREAU_DAYS_CREDIT_UPDATE_MEAN,BUREAU_DAYS_CREDIT_UPDATE_MEDIAN,BUREAU_DAYS_CREDIT_UPDATE_MAX,BUREAU_DAYS_CREDIT_UPDATE_MIN,BUREAU_DAYS_CREDIT_UPDATE_SUM,BUREAU_DAYS_CREDIT_UPDATE_STD,BUREAU_AMT_ANNUITY_COUNT,BUREAU_AMT_ANNUITY_MEAN,BUREAU_AMT_ANNUITY_MEDIAN,BUREAU_AMT_ANNUITY_MAX,BUREAU_AMT_ANNUITY_MIN,BUREAU_AMT_ANNUITY_SUM,BUREAU_AMT_ANNUITY_STD
0,100001,7,-735.000000,-857.0,-49,-1572,-5145,489.942514,7,0.0,0.0,0,0,0,0.0,7,82.428571,-179.0,1778.0,-1329.0,577.0,1032.859277,4,-825.500000,-715.0,-544.0,-1328.0,-3302.0,369.078582,0,NaN,NaN,NaN,NaN,0.000,NaN,7,0.000000,0.0,0,0,0,0.000000,7,2.076236e+05,168345.00,378000.00,85500.0,1453365.000,122544.544510,7,85240.928571,0.000,373239.00,0.0,596686.500,137485.631124,6,0.00000,0.0,0.000,0.0,0.000,0.000000,7,0.0,0.0,0.0,0.0,0.0,0.0,7,-93.142857,-155.0,-6,-155,-652,77.204120,7,3545.357143,0.0,10822.5,0.000,24817.500,4800.607529
1,100002,8,-874.000000,-1042.5,-103,-1437,-6992,431.451040,8,0.0,0.0,0,0,0,0.0,6,-349.000000,-424.5,780.0,-1072.0,-2094.0,767.490977,6,-697.500000,-939.0,-36.0,-1185.0,-4185.0,515.992539,5,1681.029,40.500,5043.645,0.0,8405.145,2363.246900,8,0.000000,0.0,0,0,0,0.000000,8,1.081319e+05,54130.50,450000.00,0.0,865055.565,146075.557435,5,49156.200000,0.000,245781.00,0.0,245781.000,109916.604716,4,7997.14125,0.0,31988.565,0.0,31988.565,15994.282500,8,0.0,0.0,0.0,0.0,0.0,0.0,8,-499.875000,-402.5,-7,-1185,-3999,518.522472,7,0.000000,0.0,0.0,0.000,0.000,0.000000
2,100003,4,-1400.750000,-1205.5,-606,-2586,-5603,909.826128,4,0.0,0.0,0,0,0,0.0,4,-544.500000,-480.0,1216.0,-2434.0,-2178.0,1492.770467,3,-1097.333333,-621.0,-540.0,-2131.0,-3292.0,896.097279,4,0.000,0.000,0.000,0.0,0.000,0.000000,4,0.000000,0.0,0,0,0,0.000000,4,2.543501e+05,92576.25,810000.00,22248.0,1017400.500,372269.465535,4,0.000000,0.000,0.00,0.0,0.000,0.000000,4,202500.00000,0.0,810000.000,0.0,810000.000,405000.000000,4,0.0,0.0,0.0,0.0,0.0,0.0,4,-816.000000,-545.0,-43,-2131,-3264,908.053963,0,NaN,NaN,NaN,NaN,0.000,NaN
3,100004,2,-867.000000,-867.0,-408,-1326,-1734,649.124025,2,0.0,0.0,0,0,0,0.0,2,-488.500000,-488.5,-382.0,-595.0,-977.0,150.613744,2,-532.500000,-532.5,-382.0,-683.0,-1065.0,212.839141,1,0.000,0.000,0.000,0.0,0.000,NaN,2,0.000000,0.0,0,0,0,0.000000,2,9.451890e+04,94518.90,94537.80,94500.0,189037.800,26.728636,2,0.000000,0.000,0.00,0.0,0.000,0.000000,2,0.00000,0.0,0.000,0.0,0.000,0.000000,2,0.0,0.0,0.0,0.0,0.0,0.0,2,-532.000000,-532.0,-382,-682,-1064,212.132034,0,NaN,NaN,NaN,NaN,0.000,NaN
4,100005,3,-190.666667,-137.0,-62,-373,-572,162.297053,3,0.0,0.0,0,0,0,0.0,3,439.333333,122.0,1324.0,-128.0,1318.0,776.274007,1,-123.000000,-123.0,-123.0,-123.0,-123.0,NaN,1,0.000,0.000,0.000,0.0,0.000,NaN,3,0.000000,0.0,0,0,0,0.000000,3,2.190420e+05,58500.00,568800.00,29826.0,657126.000,303238.426806,3,189469.500000,25321.500,543087.00,0.0,568408.500,306503.339003,3,0.00000,0.0,0.000,0.0,0.000,0.000000,3,0.0,0.0,0.0,0.0,0.0,0.0,3,-54.333333,-31.0,-11,-121,-163,58.594653,3,1420.500000,0.0,4261.5,0.000,4261.500,2460.378172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305806,456249,13,-1667.076923,-1680.0,-483,-2713,-21672,638.202353,13,0.0,0.0,0,0,0,0.0,12,-1232.333333,-1339.0,1363.0,-2499.0,-14788.0,977.587321,12,-1364.750000,-1279.0,-291.0,-2525.0,-16377.0,634.859344,5,6147.000,0.000,18945.000,0.0,30735.000,8789.042610,13,0.000000,0.0,0,0,0,0.000000,13,2.841430e+05,248692.50,765000.00,43447.5,3693858.660,216131.351490,10,16307.100000,0.000,163071.00,0.0,163071.000,51567.578032,7,0.00000,0.0,0.000,0.0,0.000,0.000000,13,0.0,0.0,0.0,0.0,0.0,0.0,13,-1064.538462,-909.0,-12,-2498,-13839,662.638868,0,NaN,NaN,NaN,NaN,0.000,NaN
305807,456250,3,-862.000000,-824.0,-760,-1002,-2586,125.395375,3,0.0,0.0,0,0,0,0.0,3,1288.333333,1797.0,2340.0,-272.0,3865.0,1378.293268,1,-760.000000,-760.0,-760.0,-760.0,-760.0,NaN,2,0.000,0.000,0.000,0.0,0.000,0.000000,3,0.000000,0.0,0,0,0,0.000000,3,1.028820e+06,483349.50,2153110.05,450000.0,3086459.550,973806.647980,3,744013.365000,391731.615,1840308.48,0.0,2232040.095,969412.527734,3,19422.79500,0.0,58268.385,0.0,58268.385,33641.267765,3,0.0,0.0,0.0,0.0,0.0,0.0,3,-60.333333,-31.0,-23,-127,-181,57.873425,3,154567.965000,51799.5,384147.0,27757.395,463703.895,199184.351009
305808,456253,4,-867.500000,-919.0,-713,-919,-3470,103.000000,4,0.0,0.0,0,0,0,0.0,4,280.500000,99.0,1113.0,-189.0,1122.0,617.861635,2,-794.000000,-794.0,-794.0,-794.0,-1588.0,0.000000,0,NaN,NaN,NaN,NaN,0.000,NaN,4,0.000000,0.0,0,0,0,0.000000,4,9.900000e+05,675000.00,2250000.00,360000.0,3960000.000,853024.032487,4,448958.250000,85518.000,1624797.00,0.0,1795833.000,788028.037473,4,0.00000,0.0,0.000,0.0,0.000,0.000000,4,0.0,0.0,0.0,0.0,0.0,0.0,4,-253.250000,-153.5,-5,-701,-1013,307.304816,3,58369.500000,58369.5,58369.5,58369.500,175108.500,0.000000
305809,456254,1,-1104.000000,-1104.0,-1104,-1104,-1104,NaN,1,0.0,0.0,0,0,0,NaN,1,-859.000000,-859.0,-859.0,-859.0,-859.0,NaN,1,-859.000000,-859.0,-859.0,-859.0,-859.0,NaN,0,NaN,NaN,NaN,NaN,0.000,NaN,1,0.000000,0.0,0,0,0,NaN,1,4.500000e+04,45000.00,45000.00,45000.0,45000.000,NaN,1,0.000000,0.000,0.00,0.0,0.000,NaN,0,NaN,NaN,NaN,NaN,0.000,NaN,1,0.0,0.0,0.0,0.0,0.0,NaN,1,-401.000000,-401.0,-401,-401,-401,NaN,1,0.000000,0.0,0.0,0.000,0.000,NaN
305810,456255,11,-1089.454545,-1020.0,-363,-2337,-11984,709.074518,11,0.0,0.0,0,0,0,0.0,11,3231.272727,315.0,27320.0,-1243.0,35544.0,8443.015422,6,-968.333333,-869.5,-712.0,-1621.0,-5810.0,335.504198,5,12056.481,15439.905,25578.000,0.0,60282.405,10594.891908,11,0.090909,0.0,1,0,1,0.301511,11,3.456290e+05,436032.00,900000.00,22995.0,3801919.500,326337.215358,8,191864.126250,126032.985,595102.50,0.0,1534913.010,219459.163931,5,0.00000,0.0,0.000,0.0,0.000,0.000000,11,0.0,0.0,0.0,0.0,0.0,0.0,11,-531.090909,-700.0,-8,-1621,-5842,541.877745,9,1081.500000,0.0,3244.5,0.000,9733.500,1622.250000

In [73]:
temp = temp.merge(bureau_agg, on = 'SK_ID_CURR', how = 'left')

In [79]:
def agg_fn_numeric(data, col, name):
    df = data.copy()
    for column in df:
        if column != col and 'SK_ID' in column:
            df.drop(column, axis = 1, inplace = True)
    
    group_ids = df[col]
    numeric_df = df.select_dtypes('number')
    numeric_df[col] = group_ids        
    
    agg = numeric_df.groupby(col).agg(['count','mean', 'max', 'min','sum']).reset_index()
    
    c = [col]
    for var in agg.columns.levels[0]:
        if var != col:
            for stat in agg.columns.levels[1][:-1]:
                c.append('{}_{}_{}'.format(name.upper(), var.upper(), stat.upper()))
    agg.columns = c
    return agg

In [80]:
agg_fn_numeric(data = bureau.drop('SK_ID_BUREAU', axis = 1), col = 'SK_ID_CURR', name = 'Bureau')

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,SK_ID_CURR,BUREAU_DAYS_CREDIT_COUNT,BUREAU_DAYS_CREDIT_MEAN,BUREAU_DAYS_CREDIT_MAX,BUREAU_DAYS_CREDIT_MIN,BUREAU_DAYS_CREDIT_SUM,BUREAU_CREDIT_DAY_OVERDUE_COUNT,BUREAU_CREDIT_DAY_OVERDUE_MEAN,BUREAU_CREDIT_DAY_OVERDUE_MAX,BUREAU_CREDIT_DAY_OVERDUE_MIN,BUREAU_CREDIT_DAY_OVERDUE_SUM,BUREAU_DAYS_CREDIT_ENDDATE_COUNT,BUREAU_DAYS_CREDIT_ENDDATE_MEAN,BUREAU_DAYS_CREDIT_ENDDATE_MAX,BUREAU_DAYS_CREDIT_ENDDATE_MIN,BUREAU_DAYS_CREDIT_ENDDATE_SUM,BUREAU_DAYS_ENDDATE_FACT_COUNT,BUREAU_DAYS_ENDDATE_FACT_MEAN,BUREAU_DAYS_ENDDATE_FACT_MAX,BUREAU_DAYS_ENDDATE_FACT_MIN,BUREAU_DAYS_ENDDATE_FACT_SUM,BUREAU_AMT_CREDIT_MAX_OVERDUE_COUNT,BUREAU_AMT_CREDIT_MAX_OVERDUE_MEAN,BUREAU_AMT_CREDIT_MAX_OVERDUE_MAX,BUREAU_AMT_CREDIT_MAX_OVERDUE_MIN,BUREAU_AMT_CREDIT_MAX_OVERDUE_SUM,BUREAU_CNT_CREDIT_PROLONG_COUNT,BUREAU_CNT_CREDIT_PROLONG_MEAN,BUREAU_CNT_CREDIT_PROLONG_MAX,BUREAU_CNT_CREDIT_PROLONG_MIN,BUREAU_CNT_CREDIT_PROLONG_SUM,BUREAU_AMT_CREDIT_SUM_COUNT,BUREAU_AMT_CREDIT_SUM_MEAN,BUREAU_AMT_CREDIT_SUM_MAX,BUREAU_AMT_CREDIT_SUM_MIN,BUREAU_AMT_CREDIT_SUM_SUM,BUREAU_AMT_CREDIT_SUM_DEBT_COUNT,BUREAU_AMT_CREDIT_SUM_DEBT_MEAN,BUREAU_AMT_CREDIT_SUM_DEBT_MAX,BUREAU_AMT_CREDIT_SUM_DEBT_MIN,BUREAU_AMT_CREDIT_SUM_DEBT_SUM,BUREAU_AMT_CREDIT_SUM_LIMIT_COUNT,BUREAU_AMT_CREDIT_SUM_LIMIT_MEAN,BUREAU_AMT_CREDIT_SUM_LIMIT_MAX,BUREAU_AMT_CREDIT_SUM_LIMIT_MIN,BUREAU_AMT_CREDIT_SUM_LIMIT_SUM,BUREAU_AMT_CREDIT_SUM_OVERDUE_COUNT,BUREAU_AMT_CREDIT_SUM_OVERDUE_MEAN,BUREAU_AMT_CREDIT_SUM_OVERDUE_MAX,BUREAU_AMT_CREDIT_SUM_OVERDUE_MIN,BUREAU_AMT_CREDIT_SUM_OVERDUE_SUM,BUREAU_DAYS_CREDIT_UPDATE_COUNT,BUREAU_DAYS_CREDIT_UPDATE_MEAN,BUREAU_DAYS_CREDIT_UPDATE_MAX,BUREAU_DAYS_CREDIT_UPDATE_MIN,BUREAU_DAYS_CREDIT_UPDATE_SUM,BUREAU_AMT_ANNUITY_COUNT,BUREAU_AMT_ANNUITY_MEAN,BUREAU_AMT_ANNUITY_MAX,BUREAU_AMT_ANNUITY_MIN,BUREAU_AMT_ANNUITY_SUM
0,100001,7,-735.000000,-49,-1572,-5145,7,0.0,0,0,0,7,82.428571,1778.0,-1329.0,577.0,4,-825.500000,-544.0,-1328.0,-3302.0,0,NaN,NaN,NaN,0.000,7,0.000000,0,0,0,7,2.076236e+05,378000.00,85500.0,1453365.000,7,85240.928571,373239.00,0.0,596686.500,6,0.00000,0.000,0.0,0.000,7,0.0,0.0,0.0,0.0,7,-93.142857,-6,-155,-652,7,3545.357143,10822.5,0.000,24817.500
1,100002,8,-874.000000,-103,-1437,-6992,8,0.0,0,0,0,6,-349.000000,780.0,-1072.0,-2094.0,6,-697.500000,-36.0,-1185.0,-4185.0,5,1681.029,5043.645,0.0,8405.145,8,0.000000,0,0,0,8,1.081319e+05,450000.00,0.0,865055.565,5,49156.200000,245781.00,0.0,245781.000,4,7997.14125,31988.565,0.0,31988.565,8,0.0,0.0,0.0,0.0,8,-499.875000,-7,-1185,-3999,7,0.000000,0.0,0.000,0.000
2,100003,4,-1400.750000,-606,-2586,-5603,4,0.0,0,0,0,4,-544.500000,1216.0,-2434.0,-2178.0,3,-1097.333333,-540.0,-2131.0,-3292.0,4,0.000,0.000,0.0,0.000,4,0.000000,0,0,0,4,2.543501e+05,810000.00,22248.0,1017400.500,4,0.000000,0.00,0.0,0.000,4,202500.00000,810000.000,0.0,810000.000,4,0.0,0.0,0.0,0.0,4,-816.000000,-43,-2131,-3264,0,NaN,NaN,NaN,0.000
3,100004,2,-867.000000,-408,-1326,-1734,2,0.0,0,0,0,2,-488.500000,-382.0,-595.0,-977.0,2,-532.500000,-382.0,-683.0,-1065.0,1,0.000,0.000,0.0,0.000,2,0.000000,0,0,0,2,9.451890e+04,94537.80,94500.0,189037.800,2,0.000000,0.00,0.0,0.000,2,0.00000,0.000,0.0,0.000,2,0.0,0.0,0.0,0.0,2,-532.000000,-382,-682,-1064,0,NaN,NaN,NaN,0.000
4,100005,3,-190.666667,-62,-373,-572,3,0.0,0,0,0,3,439.333333,1324.0,-128.0,1318.0,1,-123.000000,-123.0,-123.0,-123.0,1,0.000,0.000,0.0,0.000,3,0.000000,0,0,0,3,2.190420e+05,568800.00,29826.0,657126.000,3,189469.500000,543087.00,0.0,568408.500,3,0.00000,0.000,0.0,0.000,3,0.0,0.0,0.0,0.0,3,-54.333333,-11,-121,-163,3,1420.500000,4261.5,0.000,4261.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305806,456249,13,-1667.076923,-483,-2713,-21672,13,0.0,0,0,0,12,-1232.333333,1363.0,-2499.0,-14788.0,12,-1364.750000,-291.0,-2525.0,-16377.0,5,6147.000,18945.000,0.0,30735.000,13,0.000000,0,0,0,13,2.841430e+05,765000.00,43447.5,3693858.660,10,16307.100000,163071.00,0.0,163071.000,7,0.00000,0.000,0.0,0.000,13,0.0,0.0,0.0,0.0,13,-1064.538462,-12,-2498,-13839,0,NaN,NaN,NaN,0.000
305807,456250,3,-862.000000,-760,-1002,-2586,3,0.0,0,0,0,3,1288.333333,2340.0,-272.0,3865.0,1,-760.000000,-760.0,-760.0,-760.0,2,0.000,0.000,0.0,0.000,3,0.000000,0,0,0,3,1.028820e+06,2153110.05,450000.0,3086459.550,3,744013.365000,1840308.48,0.0,2232040.095,3,19422.79500,58268.385,0.0,58268.385,3,0.0,0.0,0.0,0.0,3,-60.333333,-23,-127,-181,3,154567.965000,384147.0,27757.395,463703.895
305808,456253,4,-867.500000,-713,-919,-3470,4,0.0,0,0,0,4,280.500000,1113.0,-189.0,1122.0,2,-794.000000,-794.0,-794.0,-1588.0,0,NaN,NaN,NaN,0.000,4,0.000000,0,0,0,4,9.900000e+05,2250000.00,360000.0,3960000.000,4,448958.250000,1624797.00,0.0,1795833.000,4,0.00000,0.000,0.0,0.000,4,0.0,0.0,0.0,0.0,4,-253.250000,-5,-701,-1013,3,58369.500000,58369.5,58369.500,175108.500
305809,456254,1,-1104.000000,-1104,-1104,-1104,1,0.0,0,0,0,1,-859.000000,-859.0,-859.0,-859.0,1,-859.000000,-859.0,-859.0,-859.0,0,NaN,NaN,NaN,0.000,1,0.000000,0,0,0,1,4.500000e+04,45000.00,45000.0,45000.000,1,0.000000,0.00,0.0,0.000,0,NaN,NaN,NaN,0.000,1,0.0,0.0,0.0,0.0,1,-401.000000,-401,-401,-401,1,0.000000,0.0,0.000,0.000
305810,456255,11,-1089.454545,-363,-2337,-11984,11,0.0,0,0,0,11,3231.272727,27320.0,-1243.0,35544.0,6,-968.333333,-712.0,-1621.0,-5810.0,5,12056.481,25578.000,0.0,60282.405,11,0.090909,1,0,1,11,3.456290e+05,900000.00,22995.0,3801919.500,8,191864.126250,595102.50,0.0,1534913.010,5,0.00000,0.000,0.0,0.000,11,0.0,0.0,0.0,0.0,11,-531.090909,-8,-1621,-5842,9,1081.500000,3244.5,0.000,9733.500

In [81]:
bureau_agg

,SK_ID_CURR,BUREAU_DAYS_CREDIT_COUNT,BUREAU_DAYS_CREDIT_MEAN,BUREAU_DAYS_CREDIT_MEDIAN,BUREAU_DAYS_CREDIT_MAX,BUREAU_DAYS_CREDIT_MIN,BUREAU_DAYS_CREDIT_SUM,BUREAU_DAYS_CREDIT_STD,BUREAU_CREDIT_DAY_OVERDUE_COUNT,BUREAU_CREDIT_DAY_OVERDUE_MEAN,BUREAU_CREDIT_DAY_OVERDUE_MEDIAN,BUREAU_CREDIT_DAY_OVERDUE_MAX,BUREAU_CREDIT_DAY_OVERDUE_MIN,BUREAU_CREDIT_DAY_OVERDUE_SUM,BUREAU_CREDIT_DAY_OVERDUE_STD,BUREAU_DAYS_CREDIT_ENDDATE_COUNT,BUREAU_DAYS_CREDIT_ENDDATE_MEAN,BUREAU_DAYS_CREDIT_ENDDATE_MEDIAN,BUREAU_DAYS_CREDIT_ENDDATE_MAX,BUREAU_DAYS_CREDIT_ENDDATE_MIN,BUREAU_DAYS_CREDIT_ENDDATE_SUM,BUREAU_DAYS_CREDIT_ENDDATE_STD,BUREAU_DAYS_ENDDATE_FACT_COUNT,BUREAU_DAYS_ENDDATE_FACT_MEAN,BUREAU_DAYS_ENDDATE_FACT_MEDIAN,BUREAU_DAYS_ENDDATE_FACT_MAX,BUREAU_DAYS_ENDDATE_FACT_MIN,BUREAU_DAYS_ENDDATE_FACT_SUM,BUREAU_DAYS_ENDDATE_FACT_STD,BUREAU_AMT_CREDIT_MAX_OVERDUE_COUNT,BUREAU_AMT_CREDIT_MAX_OVERDUE_MEAN,BUREAU_AMT_CREDIT_MAX_OVERDUE_MEDIAN,BUREAU_AMT_CREDIT_MAX_OVERDUE_MAX,BUREAU_AMT_CREDIT_MAX_OVERDUE_MIN,BUREAU_AMT_CREDIT_MAX_OVERDUE_SUM,BUREAU_AMT_CREDIT_MAX_OVERDUE_STD,BUREAU_CNT_CREDIT_PROLONG_COUNT,BUREAU_CNT_CREDIT_PROLONG_MEAN,BUREAU_CNT_CREDIT_PROLONG_MEDIAN,BUREAU_CNT_CREDIT_PROLONG_MAX,BUREAU_CNT_CREDIT_PROLONG_MIN,BUREAU_CNT_CREDIT_PROLONG_SUM,BUREAU_CNT_CREDIT_PROLONG_STD,BUREAU_AMT_CREDIT_SUM_COUNT,BUREAU_AMT_CREDIT_SUM_MEAN,BUREAU_AMT_CREDIT_SUM_MEDIAN,BUREAU_AMT_CREDIT_SUM_MAX,BUREAU_AMT_CREDIT_SUM_MIN,BUREAU_AMT_CREDIT_SUM_SUM,BUREAU_AMT_CREDIT_SUM_STD,BUREAU_AMT_CREDIT_SUM_DEBT_COUNT,BUREAU_AMT_CREDIT_SUM_DEBT_MEAN,BUREAU_AMT_CREDIT_SUM_DEBT_MEDIAN,BUREAU_AMT_CREDIT_SUM_DEBT_MAX,BUREAU_AMT_CREDIT_SUM_DEBT_MIN,BUREAU_AMT_CREDIT_SUM_DEBT_SUM,BUREAU_AMT_CREDIT_SUM_DEBT_STD,BUREAU_AMT_CREDIT_SUM_LIMIT_COUNT,BUREAU_AMT_CREDIT_SUM_LIMIT_MEAN,BUREAU_AMT_CREDIT_SUM_LIMIT_MEDIAN,BUREAU_AMT_CREDIT_SUM_LIMIT_MAX,BUREAU_AMT_CREDIT_SUM_LIMIT_MIN,BUREAU_AMT_CREDIT_SUM_LIMIT_SUM,BUREAU_AMT_CREDIT_SUM_LIMIT_STD,BUREAU_AMT_CREDIT_SUM_OVERDUE_COUNT,BUREAU_AMT_CREDIT_SUM_OVERDUE_MEAN,BUREAU_AMT_CREDIT_SUM_OVERDUE_MEDIAN,BUREAU_AMT_CREDIT_SUM_OVERDUE_MAX,BUREAU_AMT_CREDIT_SUM_OVERDUE_MIN,BUREAU_AMT_CREDIT_SUM_OVERDUE_SUM,BUREAU_AMT_CREDIT_SUM_OVERDUE_STD,BUREAU_DAYS_CREDIT_UPDATE_COUNT,BUREAU_DAYS_CREDIT_UPDATE_MEAN,BUREAU_DAYS_CREDIT_UPDATE_MEDIAN,BUREAU_DAYS_CREDIT_UPDATE_MAX,BUREAU_DAYS_CREDIT_UPDATE_MIN,BUREAU_DAYS_CREDIT_UPDATE_SUM,BUREAU_DAYS_CREDIT_UPDATE_STD,BUREAU_AMT_ANNUITY_COUNT,BUREAU_AMT_ANNUITY_MEAN,BUREAU_AMT_ANNUITY_MEDIAN,BUREAU_AMT_ANNUITY_MAX,BUREAU_AMT_ANNUITY_MIN,BUREAU_AMT_ANNUITY_SUM,BUREAU_AMT_ANNUITY_STD
0,100001,7,-735.000000,-857.0,-49,-1572,-5145,489.942514,7,0.0,0.0,0,0,0,0.0,7,82.428571,-179.0,1778.0,-1329.0,577.0,1032.859277,4,-825.500000,-715.0,-544.0,-1328.0,-3302.0,369.078582,0,NaN,NaN,NaN,NaN,0.000,NaN,7,0.000000,0.0,0,0,0,0.000000,7,2.076236e+05,168345.00,378000.00,85500.0,1453365.000,122544.544510,7,85240.928571,0.000,373239.00,0.0,596686.500,137485.631124,6,0.00000,0.0,0.000,0.0,0.000,0.000000,7,0.0,0.0,0.0,0.0,0.0,0.0,7,-93.142857,-155.0,-6,-155,-652,77.204120,7,3545.357143,0.0,10822.5,0.000,24817.500,4800.607529
1,100002,8,-874.000000,-1042.5,-103,-1437,-6992,431.451040,8,0.0,0.0,0,0,0,0.0,6,-349.000000,-424.5,780.0,-1072.0,-2094.0,767.490977,6,-697.500000,-939.0,-36.0,-1185.0,-4185.0,515.992539,5,1681.029,40.500,5043.645,0.0,8405.145,2363.246900,8,0.000000,0.0,0,0,0,0.000000,8,1.081319e+05,54130.50,450000.00,0.0,865055.565,146075.557435,5,49156.200000,0.000,245781.00,0.0,245781.000,109916.604716,4,7997.14125,0.0,31988.565,0.0,31988.565,15994.282500,8,0.0,0.0,0.0,0.0,0.0,0.0,8,-499.875000,-402.5,-7,-1185,-3999,518.522472,7,0.000000,0.0,0.0,0.000,0.000,0.000000
2,100003,4,-1400.750000,-1205.5,-606,-2586,-5603,909.826128,4,0.0,0.0,0,0,0,0.0,4,-544.500000,-480.0,1216.0,-2434.0,-2178.0,1492.770467,3,-1097.333333,-621.0,-540.0,-2131.0,-3292.0,896.097279,4,0.000,0.000,0.000,0.0,0.000,0.000000,4,0.000000,0.0,0,0,0,0.000000,4,2.543501e+05,92576.25,810000.00,22248.0,1017400.500,372269.465535,4,0.000000,0.000,0.00,0.0,0.000,0.000000,4,202500.00000,0.0,810000.000,0.0,810000.000,405000.000000,4,0.0,0.0,0.0,0.0,0.0,0.0,4,-816.000000,-545.0,-43,-2131,-3264,908.053963,0,NaN,NaN,NaN,NaN,0.000,NaN
3,100004,2,-867.000000,-867.0,-408,-1326,-1734,649.124025,2,0.0,0.0,0,0,0,0.0,2,-488.500000,-488.5,-382.0,-595.0,-977.0,150.613744,2,-532.500000,-532.5,-382.0,-683.0,-1065.0,212.839141,1,0.000,0.000,0.000,0.0,0.000,NaN,2,0.000000,0.0,0,0,0,0.000000,2,9.451890e+04,94518.90,94537.80,94500.0,189037.800,26.728636,2,0.000000,0.000,0.00,0.0,0.000,0.000000,2,0.00000,0.0,0.000,0.0,0.000,0.000000,2,0.0,0.0,0.0,0.0,0.0,0.0,2,-532.000000,-532.0,-382,-682,-1064,212.132034,0,NaN,NaN,NaN,NaN,0.000,NaN
4,100005,3,-190.666667,-137.0,-62,-373,-572,162.297053,3,0.0,0.0,0,0,0,0.0,3,439.333333,122.0,1324.0,-128.0,1318.0,776.274007,1,-123.000000,-123.0,-123.0,-123.0,-123.0,NaN,1,0.000,0.000,0.000,0.0,0.000,NaN,3,0.000000,0.0,0,0,0,0.000000,3,2.190420e+05,58500.00,568800.00,29826.0,657126.000,303238.426806,3,189469.500000,25321.500,543087.00,0.0,568408.500,306503.339003,3,0.00000,0.0,0.000,0.0,0.000,0.000000,3,0.0,0.0,0.0,0.0,0.0,0.0,3,-54.333333,-31.0,-11,-121,-163,58.594653,3,1420.500000,0.0,4261.5,0.000,4261.500,2460.378172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305806,456249,13,-1667.076923,-1680.0,-483,-2713,-21672,638.202353,13,0.0,0.0,0,0,0,0.0,12,-1232.333333,-1339.0,1363.0,-2499.0,-14788.0,977.587321,12,-1364.750000,-1279.0,-291.0,-2525.0,-16377.0,634.859344,5,6147.000,0.000,18945.000,0.0,30735.000,8789.042610,13,0.000000,0.0,0,0,0,0.000000,13,2.841430e+05,248692.50,765000.00,43447.5,3693858.660,216131.351490,10,16307.100000,0.000,163071.00,0.0,163071.000,51567.578032,7,0.00000,0.0,0.000,0.0,0.000,0.000000,13,0.0,0.0,0.0,0.0,0.0,0.0,13,-1064.538462,-909.0,-12,-2498,-13839,662.638868,0,NaN,NaN,NaN,NaN,0.000,NaN
305807,456250,3,-862.000000,-824.0,-760,-1002,-2586,125.395375,3,0.0,0.0,0,0,0,0.0,3,1288.333333,1797.0,2340.0,-272.0,3865.0,1378.293268,1,-760.000000,-760.0,-760.0,-760.0,-760.0,NaN,2,0.000,0.000,0.000,0.0,0.000,0.000000,3,0.000000,0.0,0,0,0,0.000000,3,1.028820e+06,483349.50,2153110.05,450000.0,3086459.550,973806.647980,3,744013.365000,391731.615,1840308.48,0.0,2232040.095,969412.527734,3,19422.79500,0.0,58268.385,0.0,58268.385,33641.267765,3,0.0,0.0,0.0,0.0,0.0,0.0,3,-60.333333,-31.0,-23,-127,-181,57.873425,3,154567.965000,51799.5,384147.0,27757.395,463703.895,199184.351009
305808,456253,4,-867.500000,-919.0,-713,-919,-3470,103.000000,4,0.0,0.0,0,0,0,0.0,4,280.500000,99.0,1113.0,-189.0,1122.0,617.861635,2,-794.000000,-794.0,-794.0,-794.0,-1588.0,0.000000,0,NaN,NaN,NaN,NaN,0.000,NaN,4,0.000000,0.0,0,0,0,0.000000,4,9.900000e+05,675000.00,2250000.00,360000.0,3960000.000,853024.032487,4,448958.250000,85518.000,1624797.00,0.0,1795833.000,788028.037473,4,0.00000,0.0,0.000,0.0,0.000,0.000000,4,0.0,0.0,0.0,0.0,0.0,0.0,4,-253.250000,-153.5,-5,-701,-1013,307.304816,3,58369.500000,58369.5,58369.5,58369.500,175108.500,0.000000
305809,456254,1,-1104.000000,-1104.0,-1104,-1104,-1104,NaN,1,0.0,0.0,0,0,0,NaN,1,-859.000000,-859.0,-859.0,-859.0,-859.0,NaN,1,-859.000000,-859.0,-859.0,-859.0,-859.0,NaN,0,NaN,NaN,NaN,NaN,0.000,NaN,1,0.000000,0.0,0,0,0,NaN,1,4.500000e+04,45000.00,45000.00,45000.0,45000.000,NaN,1,0.000000,0.000,0.00,0.0,0.000,NaN,0,NaN,NaN,NaN,NaN,0.000,NaN,1,0.0,0.0,0.0,0.0,0.0,NaN,1,-401.000000,-401.0,-401,-401,-401,NaN,1,0.000000,0.0,0.0,0.000,0.000,NaN
305810,456255,11,-1089.454545,-1020.0,-363,-2337,-11984,709.074518,11,0.0,0.0,0,0,0,0.0,11,3231.272727,315.0,27320.0,-1243.0,35544.0,8443.015422,6,-968.333333,-869.5,-712.0,-1621.0,-5810.0,335.504198,5,12056.481,15439.905,25578.000,0.0,60282.405,10594.891908,11,0.090909,0.0,1,0,1,0.301511,11,3.456290e+05,436032.00,900000.00,22995.0,3801919.500,326337.215358,8,191864.126250,126032.985,595102.50,0.0,1534913.010,219459.163931,5,0.00000,0.0,0.000,0.0,0.000,0.000000,11,0.0,0.0,0.0,0.0,0.0,0.0,11,-531.090909,-700.0,-8,-1621,-5842,541.877745,9,1081.500000,0.0,3244.5,0.000,9733.500,1622.250000

In [82]:
categorical = pd.get_dummies(bureau.select_dtypes('object'))
categorical['SK_ID_CURR'] = bureau['SK_ID_CURR']

In [83]:
categorical_grouped = categorical.groupby('SK_ID_CURR').agg(['sum', 'mean'])

In [84]:
categorical_grouped

           CREDIT_ACTIVE_Active           CREDIT_ACTIVE_Bad debt       \
                            sum      mean                    sum mean
SK_ID_CURR
100001                        3  0.428571                      0  0.0
100002                        2  0.250000                      0  0.0
100003                        1  0.250000                      0  0.0
100004                        0  0.000000                      0  0.0
100005                        2  0.666667                      0  0.0
...                         ...       ...                    ...  ...
456249                        2  0.153846                      0  0.0
456250                        2  0.666667                      0  0.0
456253                        2  0.500000                      0  0.0
456254                        0  0.000000                      0  0.0
456255                        5  0.454545                      0  0.0

           CREDIT_ACTIVE_Closed           CREDIT_ACTIVE_Sold       \
                            sum      mean                sum mean
SK_ID_CURR
100001                        4  0.571429                  0  0.0
100002                        6  0.750000                  0  0.0
100003                        3  0.750000                  0  0.0
100004                        2  1.000000                  0  0.0
100005                        1  0.333333                  0  0.0
...                         ...       ...                ...  ...
456249                       11  0.846154                  0  0.0
456250                        1  0.333333                  0  0.0
456253                        2  0.500000                  0  0.0
456254                        1  1.000000                  0  0.0
456255                        6  0.545455                  0  0.0

           CREDIT_CURRENCY_currency 1      CREDIT_CURRENCY_currency 2       \
                                  sum mean                        sum mean
SK_ID_CURR
100001                              7  1.0                          0  0.0
100002                              8  1.0                          0  0.0
100003                              4  1.0                          0  0.0
100004                              2  1.0                          0  0.0
100005                              3  1.0                          0  0.0
...                               ...  ...                        ...  ...
456249                             13  1.0                          0  0.0
456250                              3  1.0                          0  0.0
456253                              4  1.0                          0  0.0
456254                              1  1.0                          0  0.0
456255                             11  1.0                          0  0.0

           CREDIT_CURRENCY_currency 3      CREDIT_CURRENCY_currency 4       \
                                  sum mean                        sum mean
SK_ID_CURR
100001                              0  0.0                          0  0.0
100002                              0  0.0                          0  0.0
100003                              0  0.0                          0  0.0
100004                              0  0.0                          0  0.0
100005                              0  0.0                          0  0.0
...                               ...  ...                        ...  ...
456249                              0  0.0                          0  0.0
456250                              0  0.0                          0  0.0
456253                              0  0.0                          0  0.0
456254                              0  0.0                          0  0.0
456255                              0  0.0                          0  0.0

           CREDIT_TYPE_Another type of loan           CREDIT_TYPE_Car loan  \
                                        sum      mean                  sum
SK_ID_CURR
100001                                    0  0.000000                    0
100002                                    0  0.000000                    0
100003                                    0  0.000000                    0
100004                                    0  0.000000                    0
100005                                    0  0.000000                    0
...                                     ...       ...                  ...
456249                                    1  0.076923                    0
456250                                    0  0.000000                    0
456253                                    0  0.000000                    0
456254                                    0  0.000000                    0
456255                                    0  0.000000                    0

                CREDIT_TYPE_Cash loan (non-earmarked)       \
           mean                                   sum mean
SK_ID_CURR
100001      0.0                                     0  0.0
100002      0.0                                     0  0.0
100003      0.0                                     0  0.0
100004      0.0                                     0  0.0
100005      0.0                                     0  0.0
...         ...                                   ...  ...
456249      0.0                                     0  0.0
456250      0.0                                     0  0.0
456253      0.0                                     0  0.0
456254      0.0                                     0  0.0
456255      0.0                                     0  0.0

           CREDIT_TYPE_Consumer credit           CREDIT_TYPE_Credit card  \
                                   sum      mean                     sum
SK_ID_CURR
100001                               7  1.000000                       0
100002                               4  0.500000                       4
100003                               2  0.500000                       2
100004                               2  1.000000                       0
100005                               2  0.666667                       1
...                                ...       ...                     ...
456249                               9  0.692308                       3
456250                               2  0.666667                       1
456253                               3  0.750000                       1
456254                               1  1.000000                       0
456255                               9  0.818182                       2

                     CREDIT_TYPE_Interbank credit       \
                mean                          sum mean
SK_ID_CURR
100001      0.000000                            0  0.0
100002      0.500000                            0  0.0
100003      0.500000                            0  0.0
100004      0.000000                            0  0.0
100005      0.333333                            0  0.0
...              ...                          ...  ...
456249      0.230769                            0  0.0
456250      0.333333                            0  0.0
456253      0.250000                            0  0.0
456254      0.000000                            0  0.0
456255      0.181818                            0  0.0

           CREDIT_TYPE_Loan for business development       \
                                                 sum mean
SK_ID_CURR
100001                                             0  0.0
100002                                             0  0.0
100003                                             0  0.0
100004                                             0  0.0
100005                                             0  0.0
...                                              ...  ...
456249                                             0  0.0
456250                                             0  0.0
456253                                             0  0.0
456254                                             0  0.0
456255                                             0  0.0

           CREDIT_TYPE_Loan for purchase of shares (margin lending)       \
                                                                sum mean
SK_ID_CURR
100001                                                      0        0.0
100002                                                      0        0.0
100003                                                      0        0.0
100004                                                      0        0.0
100005                                                      0        0.0
...                                                       ...        ...
456249                                                      0        0.0
456250                                                      0        0.0
456253                                                      0        0.0
456254                                                      0        0.0
456255                                                      0        0.0

           CREDIT_TYPE_Loan for the purchase of equipment       \
                                                      sum mean
SK_ID_CURR
100001                                                  0  0.0
100002                                                  0  0.0
100003                                                  0  0.0
100004                                                  0  0.0
100005                                                  0  0.0
...                                                   ...  ...
456249                                                  0  0.0
456250                                                  0  0.0
456253                                                  0  0.0
456254                                                  0  0.0
456255                                                  0  0.0

           CREDIT_TYPE_Loan for working capital replenishment       \
                                                          sum mean
SK_ID_CURR
100001                                                      0  0.0
100002                                                      0  0.0
100003                                                      0  0.0
100004                                                      0  0.0
100005                                                      0  0.0
...                                                       ...  ...
456249                                                      0  0.0
456250                                                      0  0.0
456253                                                      0  0.0
456254                                                      0  0.0
456255                                                      0  0.0

           CREDIT_TYPE_Microloan      CREDIT_TYPE_Mobile operator loan       \
                             sum mean                              sum mean
SK_ID_CURR
100001                         0  0.0                                0  0.0
100002                         0  0.0                                0  0.0
100003                         0  0.0                                0  0.0
100004                         0  0.0                                0  0.0
100005                         0  0.0                                0  0.0
...                          ...  ...                              ...  ...
456249                         0  0.0                                0  0.0
456250                         0  0.0                                0  0.0
456253                         0  0.0                                0  0.0
456254                         0  0.0                                0  0.0
456255                         0  0.0                                0  0.0

           CREDIT_TYPE_Mortgage      CREDIT_TYPE_Real estate loan       \
                            sum mean                          sum mean
SK_ID_CURR
100001                        0  0.0                            0  0.0
100002                        0  0.0                            0  0.0
100003                        0  0.0                            0  0.0
100004                        0  0.0                            0  0.0
100005                        0  0.0                            0  0.0
...                         ...  ...                          ...  ...
456249                        0  0.0                            0  0.0
456250                        0  0.0                            0  0.0
456253                        0  0.0                            0  0.0
456254                        0  0.0                            0  0.0
456255                        0  0.0                            0  0.0

           CREDIT_TYPE_Unknown type of loan
                                        sum mean
SK_ID_CURR
100001                                    0  0.0
100002                                    0  0.0
100003                                    0  0.0
100004                                    0  0.0
100005                                    0  0.0
...                                     ...  ...
456249                                    0  0.0
456250                                    0  0.0
456253                                    0  0.0
456254                                    0  0.0
456255                                    0  0.0

[305811 rows x 46 columns]

In [85]:
categorical_grouped.columns.levels[0]

Index(['CREDIT_ACTIVE_Active', 'CREDIT_ACTIVE_Bad debt',
       'CREDIT_ACTIVE_Closed', 'CREDIT_ACTIVE_Sold',
       'CREDIT_CURRENCY_currency 1', 'CREDIT_CURRENCY_currency 2',
       'CREDIT_CURRENCY_currency 3', 'CREDIT_CURRENCY_currency 4',
       'CREDIT_TYPE_Another type of loan', 'CREDIT_TYPE_Car loan',
       'CREDIT_TYPE_Cash loan (non-earmarked)', 'CREDIT_TYPE_Consumer credit',
       'CREDIT_TYPE_Credit card', 'CREDIT_TYPE_Interbank credit',
       'CREDIT_TYPE_Loan for business development',
       'CREDIT_TYPE_Loan for purchase of shares (margin lending)',
       'CREDIT_TYPE_Loan for the purchase of equipment',
       'CREDIT_TYPE_Loan for working capital replenishment',
       'CREDIT_TYPE_Microloan', 'CREDIT_TYPE_Mobile operator loan',
       'CREDIT_TYPE_Mortgage', 'CREDIT_TYPE_Real estate loan',
       'CREDIT_TYPE_Unknown type of loan'],
      dtype='object')

In [86]:
gr = 'SK_ID_CURR'
columns = []
for col in categorical_grouped.columns.levels[0]:
    if col != gr:
        for stat in ['COUNT', 'COUNT_NORM']:
            columns.append('{}_{}'.format(col.upper(), stat.upper()))

In [87]:
categorical_grouped.columns = columns

In [88]:
categorical_grouped

,CREDIT_ACTIVE_ACTIVE_COUNT,CREDIT_ACTIVE_ACTIVE_COUNT_NORM,CREDIT_ACTIVE_BAD DEBT_COUNT,CREDIT_ACTIVE_BAD DEBT_COUNT_NORM,CREDIT_ACTIVE_CLOSED_COUNT,CREDIT_ACTIVE_CLOSED_COUNT_NORM,CREDIT_ACTIVE_SOLD_COUNT,CREDIT_ACTIVE_SOLD_COUNT_NORM,CREDIT_CURRENCY_CURRENCY 1_COUNT,CREDIT_CURRENCY_CURRENCY 1_COUNT_NORM,CREDIT_CURRENCY_CURRENCY 2_COUNT,CREDIT_CURRENCY_CURRENCY 2_COUNT_NORM,CREDIT_CURRENCY_CURRENCY 3_COUNT,CREDIT_CURRENCY_CURRENCY 3_COUNT_NORM,CREDIT_CURRENCY_CURRENCY 4_COUNT,CREDIT_CURRENCY_CURRENCY 4_COUNT_NORM,CREDIT_TYPE_ANOTHER TYPE OF LOAN_COUNT,CREDIT_TYPE_ANOTHER TYPE OF LOAN_COUNT_NORM,CREDIT_TYPE_CAR LOAN_COUNT,CREDIT_TYPE_CAR LOAN_COUNT_NORM,CREDIT_TYPE_CASH LOAN (NON-EARMARKED)_COUNT,CREDIT_TYPE_CASH LOAN (NON-EARMARKED)_COUNT_NORM,CREDIT_TYPE_CONSUMER CREDIT_COUNT,CREDIT_TYPE_CONSUMER CREDIT_COUNT_NORM,CREDIT_TYPE_CREDIT CARD_COUNT,CREDIT_TYPE_CREDIT CARD_COUNT_NORM,CREDIT_TYPE_INTERBANK CREDIT_COUNT,CREDIT_TYPE_INTERBANK CREDIT_COUNT_NORM,CREDIT_TYPE_LOAN FOR BUSINESS DEVELOPMENT_COUNT,CREDIT_TYPE_LOAN FOR BUSINESS DEVELOPMENT_COUNT_NORM,CREDIT_TYPE_LOAN FOR PURCHASE OF SHARES (MARGIN LENDING)_COUNT,CREDIT_TYPE_LOAN FOR PURCHASE OF SHARES (MARGIN LENDING)_COUNT_NORM,CREDIT_TYPE_LOAN FOR THE PURCHASE OF EQUIPMENT_COUNT,CREDIT_TYPE_LOAN FOR THE PURCHASE OF EQUIPMENT_COUNT_NORM,CREDIT_TYPE_LOAN FOR WORKING CAPITAL REPLENISHMENT_COUNT,CREDIT_TYPE_LOAN FOR WORKING CAPITAL REPLENISHMENT_COUNT_NORM,CREDIT_TYPE_MICROLOAN_COUNT,CREDIT_TYPE_MICROLOAN_COUNT_NORM,CREDIT_TYPE_MOBILE OPERATOR LOAN_COUNT,CREDIT_TYPE_MOBILE OPERATOR LOAN_COUNT_NORM,CREDIT_TYPE_MORTGAGE_COUNT,CREDIT_TYPE_MORTGAGE_COUNT_NORM,CREDIT_TYPE_REAL ESTATE LOAN_COUNT,CREDIT_TYPE_REAL ESTATE LOAN_COUNT_NORM,CREDIT_TYPE_UNKNOWN TYPE OF LOAN_COUNT,CREDIT_TYPE_UNKNOWN TYPE OF LOAN_COUNT_NORM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100001,3,0.428571,0,0.0,4,0.571429,0,0.0,7,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,7,1.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100002,2,0.250000,0,0.0,6,0.750000,0,0.0,8,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,4,0.500000,4,0.500000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100003,1,0.250000,0,0.0,3,0.750000,0,0.0,4,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,0.500000,2,0.500000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100004,0,0.000000,0,0.0,2,1.000000,0,0.0,2,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,1.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100005,2,0.666667,0,0.0,1,0.333333,0,0.0,3,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,0.666667,1,0.333333,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456249,2,0.153846,0,0.0,11,0.846154,0,0.0,13,1.0,0,0.0,0,0.0,0,0.0,1,0.076923,0,0.0,0,0.0,9,0.692308,3,0.230769,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456250,2,0.666667,0,0.0,1,0.333333,0,0.0,3,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,0.666667,1,0.333333,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456253,2,0.500000,0,0.0,2,0.500000,0,0.0,4,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,3,0.750000,1,0.250000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456254,0,0.000000,0,0.0,1,1.000000,0,0.0,1,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,1.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456255,5,0.454545,0,0.0,6,0.545455,0,0.0,11,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,9,0.818182,2,0.181818,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0

In [89]:
def agg_fn_categorical(data, col, name):
    df = data.copy()
    for column in df:
        if column != col and 'SK_ID' in column:
            df.drop(column, axis = 1, inplace = True)
        
    group_ids = df[col]
    categorical_df = pd.get_dummies(df.select_dtypes('object'))
    categorical_df[col] = group_ids 

    agg = categorical_df.groupby(col).agg(['sum', 'mean'])
    
    columns = []
    for var in agg.columns.levels[0]:
        for stat in ['COUNT', 'COUNT_NORM']:
            columns.append('{}_{}_{}'.format(name.upper(), var.upper(), stat))

    agg.columns = columns
    return agg

In [90]:
agg_fn_categorical(bureau, 'SK_ID_CURR', 'BUREAU')

,BUREAU_CREDIT_ACTIVE_ACTIVE_COUNT,BUREAU_CREDIT_ACTIVE_ACTIVE_COUNT_NORM,BUREAU_CREDIT_ACTIVE_BAD DEBT_COUNT,BUREAU_CREDIT_ACTIVE_BAD DEBT_COUNT_NORM,BUREAU_CREDIT_ACTIVE_CLOSED_COUNT,BUREAU_CREDIT_ACTIVE_CLOSED_COUNT_NORM,BUREAU_CREDIT_ACTIVE_SOLD_COUNT,BUREAU_CREDIT_ACTIVE_SOLD_COUNT_NORM,BUREAU_CREDIT_CURRENCY_CURRENCY 1_COUNT,BUREAU_CREDIT_CURRENCY_CURRENCY 1_COUNT_NORM,BUREAU_CREDIT_CURRENCY_CURRENCY 2_COUNT,BUREAU_CREDIT_CURRENCY_CURRENCY 2_COUNT_NORM,BUREAU_CREDIT_CURRENCY_CURRENCY 3_COUNT,BUREAU_CREDIT_CURRENCY_CURRENCY 3_COUNT_NORM,BUREAU_CREDIT_CURRENCY_CURRENCY 4_COUNT,BUREAU_CREDIT_CURRENCY_CURRENCY 4_COUNT_NORM,BUREAU_CREDIT_TYPE_ANOTHER TYPE OF LOAN_COUNT,BUREAU_CREDIT_TYPE_ANOTHER TYPE OF LOAN_COUNT_NORM,BUREAU_CREDIT_TYPE_CAR LOAN_COUNT,BUREAU_CREDIT_TYPE_CAR LOAN_COUNT_NORM,BUREAU_CREDIT_TYPE_CASH LOAN (NON-EARMARKED)_COUNT,BUREAU_CREDIT_TYPE_CASH LOAN (NON-EARMARKED)_COUNT_NORM,BUREAU_CREDIT_TYPE_CONSUMER CREDIT_COUNT,BUREAU_CREDIT_TYPE_CONSUMER CREDIT_COUNT_NORM,BUREAU_CREDIT_TYPE_CREDIT CARD_COUNT,BUREAU_CREDIT_TYPE_CREDIT CARD_COUNT_NORM,BUREAU_CREDIT_TYPE_INTERBANK CREDIT_COUNT,BUREAU_CREDIT_TYPE_INTERBANK CREDIT_COUNT_NORM,BUREAU_CREDIT_TYPE_LOAN FOR BUSINESS DEVELOPMENT_COUNT,BUREAU_CREDIT_TYPE_LOAN FOR BUSINESS DEVELOPMENT_COUNT_NORM,BUREAU_CREDIT_TYPE_LOAN FOR PURCHASE OF SHARES (MARGIN LENDING)_COUNT,BUREAU_CREDIT_TYPE_LOAN FOR PURCHASE OF SHARES (MARGIN LENDING)_COUNT_NORM,BUREAU_CREDIT_TYPE_LOAN FOR THE PURCHASE OF EQUIPMENT_COUNT,BUREAU_CREDIT_TYPE_LOAN FOR THE PURCHASE OF EQUIPMENT_COUNT_NORM,BUREAU_CREDIT_TYPE_LOAN FOR WORKING CAPITAL REPLENISHMENT_COUNT,BUREAU_CREDIT_TYPE_LOAN FOR WORKING CAPITAL REPLENISHMENT_COUNT_NORM,BUREAU_CREDIT_TYPE_MICROLOAN_COUNT,BUREAU_CREDIT_TYPE_MICROLOAN_COUNT_NORM,BUREAU_CREDIT_TYPE_MOBILE OPERATOR LOAN_COUNT,BUREAU_CREDIT_TYPE_MOBILE OPERATOR LOAN_COUNT_NORM,BUREAU_CREDIT_TYPE_MORTGAGE_COUNT,BUREAU_CREDIT_TYPE_MORTGAGE_COUNT_NORM,BUREAU_CREDIT_TYPE_REAL ESTATE LOAN_COUNT,BUREAU_CREDIT_TYPE_REAL ESTATE LOAN_COUNT_NORM,BUREAU_CREDIT_TYPE_UNKNOWN TYPE OF LOAN_COUNT,BUREAU_CREDIT_TYPE_UNKNOWN TYPE OF LOAN_COUNT_NORM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100001,3,0.428571,0,0.0,4,0.571429,0,0.0,7,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,7,1.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100002,2,0.250000,0,0.0,6,0.750000,0,0.0,8,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,4,0.500000,4,0.500000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100003,1,0.250000,0,0.0,3,0.750000,0,0.0,4,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,0.500000,2,0.500000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100004,0,0.000000,0,0.0,2,1.000000,0,0.0,2,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,1.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100005,2,0.666667,0,0.0,1,0.333333,0,0.0,3,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,0.666667,1,0.333333,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456249,2,0.153846,0,0.0,11,0.846154,0,0.0,13,1.0,0,0.0,0,0.0,0,0.0,1,0.076923,0,0.0,0,0.0,9,0.692308,3,0.230769,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456250,2,0.666667,0,0.0,1,0.333333,0,0.0,3,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,0.666667,1,0.333333,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456253,2,0.500000,0,0.0,2,0.500000,0,0.0,4,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,3,0.750000,1,0.250000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456254,0,0.000000,0,0.0,1,1.000000,0,0.0,1,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,1.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456255,5,0.454545,0,0.0,6,0.545455,0,0.0,11,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,9,0.818182,2,0.181818,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0

In [91]:
categorical_grouped

,CREDIT_ACTIVE_ACTIVE_COUNT,CREDIT_ACTIVE_ACTIVE_COUNT_NORM,CREDIT_ACTIVE_BAD DEBT_COUNT,CREDIT_ACTIVE_BAD DEBT_COUNT_NORM,CREDIT_ACTIVE_CLOSED_COUNT,CREDIT_ACTIVE_CLOSED_COUNT_NORM,CREDIT_ACTIVE_SOLD_COUNT,CREDIT_ACTIVE_SOLD_COUNT_NORM,CREDIT_CURRENCY_CURRENCY 1_COUNT,CREDIT_CURRENCY_CURRENCY 1_COUNT_NORM,CREDIT_CURRENCY_CURRENCY 2_COUNT,CREDIT_CURRENCY_CURRENCY 2_COUNT_NORM,CREDIT_CURRENCY_CURRENCY 3_COUNT,CREDIT_CURRENCY_CURRENCY 3_COUNT_NORM,CREDIT_CURRENCY_CURRENCY 4_COUNT,CREDIT_CURRENCY_CURRENCY 4_COUNT_NORM,CREDIT_TYPE_ANOTHER TYPE OF LOAN_COUNT,CREDIT_TYPE_ANOTHER TYPE OF LOAN_COUNT_NORM,CREDIT_TYPE_CAR LOAN_COUNT,CREDIT_TYPE_CAR LOAN_COUNT_NORM,CREDIT_TYPE_CASH LOAN (NON-EARMARKED)_COUNT,CREDIT_TYPE_CASH LOAN (NON-EARMARKED)_COUNT_NORM,CREDIT_TYPE_CONSUMER CREDIT_COUNT,CREDIT_TYPE_CONSUMER CREDIT_COUNT_NORM,CREDIT_TYPE_CREDIT CARD_COUNT,CREDIT_TYPE_CREDIT CARD_COUNT_NORM,CREDIT_TYPE_INTERBANK CREDIT_COUNT,CREDIT_TYPE_INTERBANK CREDIT_COUNT_NORM,CREDIT_TYPE_LOAN FOR BUSINESS DEVELOPMENT_COUNT,CREDIT_TYPE_LOAN FOR BUSINESS DEVELOPMENT_COUNT_NORM,CREDIT_TYPE_LOAN FOR PURCHASE OF SHARES (MARGIN LENDING)_COUNT,CREDIT_TYPE_LOAN FOR PURCHASE OF SHARES (MARGIN LENDING)_COUNT_NORM,CREDIT_TYPE_LOAN FOR THE PURCHASE OF EQUIPMENT_COUNT,CREDIT_TYPE_LOAN FOR THE PURCHASE OF EQUIPMENT_COUNT_NORM,CREDIT_TYPE_LOAN FOR WORKING CAPITAL REPLENISHMENT_COUNT,CREDIT_TYPE_LOAN FOR WORKING CAPITAL REPLENISHMENT_COUNT_NORM,CREDIT_TYPE_MICROLOAN_COUNT,CREDIT_TYPE_MICROLOAN_COUNT_NORM,CREDIT_TYPE_MOBILE OPERATOR LOAN_COUNT,CREDIT_TYPE_MOBILE OPERATOR LOAN_COUNT_NORM,CREDIT_TYPE_MORTGAGE_COUNT,CREDIT_TYPE_MORTGAGE_COUNT_NORM,CREDIT_TYPE_REAL ESTATE LOAN_COUNT,CREDIT_TYPE_REAL ESTATE LOAN_COUNT_NORM,CREDIT_TYPE_UNKNOWN TYPE OF LOAN_COUNT,CREDIT_TYPE_UNKNOWN TYPE OF LOAN_COUNT_NORM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100001,3,0.428571,0,0.0,4,0.571429,0,0.0,7,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,7,1.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100002,2,0.250000,0,0.0,6,0.750000,0,0.0,8,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,4,0.500000,4,0.500000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100003,1,0.250000,0,0.0,3,0.750000,0,0.0,4,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,0.500000,2,0.500000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100004,0,0.000000,0,0.0,2,1.000000,0,0.0,2,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,1.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
100005,2,0.666667,0,0.0,1,0.333333,0,0.0,3,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,0.666667,1,0.333333,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456249,2,0.153846,0,0.0,11,0.846154,0,0.0,13,1.0,0,0.0,0,0.0,0,0.0,1,0.076923,0,0.0,0,0.0,9,0.692308,3,0.230769,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456250,2,0.666667,0,0.0,1,0.333333,0,0.0,3,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,2,0.666667,1,0.333333,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456253,2,0.500000,0,0.0,2,0.500000,0,0.0,4,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,3,0.750000,1,0.250000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456254,0,0.000000,0,0.0,1,1.000000,0,0.0,1,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,1,1.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
456255,5,0.454545,0,0.0,6,0.545455,0,0.0,11,1.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0,9,0.818182,2,0.181818,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0

In [92]:
bureau_bal = pd.read_csv('../input/home-credit-default-risk/bureau_balance.csv')

In [93]:
bureau_bal.head()

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C

In [94]:
bureau_bal_agg_conti = agg_fn_numeric(bureau_bal, 'SK_ID_BUREAU', 'BUREAU_BAL')
bureau_bal_agg_cat = agg_fn_categorical(bureau_bal, 'SK_ID_BUREAU', 'BUREAU_BAL')

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [95]:
bureau_bal_agg_conti.shape

(817395, 6)

In [96]:
bureau_bal_agg_cat.shape

(817395, 16)

In [97]:
bureau_agg_merged = bureau_bal_agg_cat.merge(bureau_bal_agg_conti, on = 'SK_ID_BUREAU', how = 'outer')

In [98]:
bureau_agg_merged

,SK_ID_BUREAU,BUREAU_BAL_STATUS_0_COUNT,BUREAU_BAL_STATUS_0_COUNT_NORM,BUREAU_BAL_STATUS_1_COUNT,BUREAU_BAL_STATUS_1_COUNT_NORM,BUREAU_BAL_STATUS_2_COUNT,BUREAU_BAL_STATUS_2_COUNT_NORM,BUREAU_BAL_STATUS_3_COUNT,BUREAU_BAL_STATUS_3_COUNT_NORM,BUREAU_BAL_STATUS_4_COUNT,BUREAU_BAL_STATUS_4_COUNT_NORM,BUREAU_BAL_STATUS_5_COUNT,BUREAU_BAL_STATUS_5_COUNT_NORM,BUREAU_BAL_STATUS_C_COUNT,BUREAU_BAL_STATUS_C_COUNT_NORM,BUREAU_BAL_STATUS_X_COUNT,BUREAU_BAL_STATUS_X_COUNT_NORM,BUREAU_BAL_MONTHS_BALANCE_COUNT,BUREAU_BAL_MONTHS_BALANCE_MEAN,BUREAU_BAL_MONTHS_BALANCE_MAX,BUREAU_BAL_MONTHS_BALANCE_MIN,BUREAU_BAL_MONTHS_BALANCE_SUM
0,5001709,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,86,0.886598,11,0.113402,97,-48.0,0,-96,-4656
1,5001710,5,0.060241,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,48,0.578313,30,0.361446,83,-41.0,0,-82,-3403
2,5001711,3,0.750000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,1,0.250000,4,-1.5,0,-3,-6
3,5001712,10,0.526316,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,9,0.473684,0,0.000000,19,-9.0,0,-18,-171
4,5001713,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,22,1.000000,22,-10.5,0,-21,-231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817390,6842884,9,0.187500,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,20,0.416667,19,0.395833,48,-23.5,0,-47,-1128
817391,6842885,12,0.500000,0,0.000000,0,0.0,0,0.0,0,0.0,12,0.5,0,0.000000,0,0.000000,24,-11.5,0,-23,-276
817392,6842886,8,0.242424,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,25,0.757576,0,0.000000,33,-16.0,0,-32,-528
817393,6842887,6,0.162162,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,31,0.837838,0,0.000000,37,-18.0,0,-36,-666
817394,6842888,9,0.145161,1,0.016129,0,0.0,0,0.0,0,0.0,0,0.0,52,0.838710,0,0.000000,62,-30.5,0,-61,-1891

In [101]:
temp = bureau_agg_merged.merge(bureau[['SK_ID_BUREAU', 'SK_ID_CURR']], how = 'left', on = 'SK_ID_BUREAU')

In [102]:
temp

,SK_ID_BUREAU,BUREAU_BAL_STATUS_0_COUNT,BUREAU_BAL_STATUS_0_COUNT_NORM,BUREAU_BAL_STATUS_1_COUNT,BUREAU_BAL_STATUS_1_COUNT_NORM,BUREAU_BAL_STATUS_2_COUNT,BUREAU_BAL_STATUS_2_COUNT_NORM,BUREAU_BAL_STATUS_3_COUNT,BUREAU_BAL_STATUS_3_COUNT_NORM,BUREAU_BAL_STATUS_4_COUNT,BUREAU_BAL_STATUS_4_COUNT_NORM,BUREAU_BAL_STATUS_5_COUNT,BUREAU_BAL_STATUS_5_COUNT_NORM,BUREAU_BAL_STATUS_C_COUNT,BUREAU_BAL_STATUS_C_COUNT_NORM,BUREAU_BAL_STATUS_X_COUNT,BUREAU_BAL_STATUS_X_COUNT_NORM,BUREAU_BAL_MONTHS_BALANCE_COUNT,BUREAU_BAL_MONTHS_BALANCE_MEAN,BUREAU_BAL_MONTHS_BALANCE_MAX,BUREAU_BAL_MONTHS_BALANCE_MIN,BUREAU_BAL_MONTHS_BALANCE_SUM,SK_ID_CURR
0,5001709,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,86,0.886598,11,0.113402,97,-48.0,0,-96,-4656,NaN
1,5001710,5,0.060241,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,48,0.578313,30,0.361446,83,-41.0,0,-82,-3403,162368.0
2,5001711,3,0.750000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,1,0.250000,4,-1.5,0,-3,-6,162368.0
3,5001712,10,0.526316,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,9,0.473684,0,0.000000,19,-9.0,0,-18,-171,162368.0
4,5001713,0,0.000000,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,22,1.000000,22,-10.5,0,-21,-231,150635.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817390,6842884,9,0.187500,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,20,0.416667,19,0.395833,48,-23.5,0,-47,-1128,387020.0
817391,6842885,12,0.500000,0,0.000000,0,0.0,0,0.0,0,0.0,12,0.5,0,0.000000,0,0.000000,24,-11.5,0,-23,-276,387020.0
817392,6842886,8,0.242424,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,25,0.757576,0,0.000000,33,-16.0,0,-32,-528,387020.0
817393,6842887,6,0.162162,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,31,0.837838,0,0.000000,37,-18.0,0,-36,-666,387020.0
817394,6842888,9,0.145161,1,0.016129,0,0.0,0,0.0,0,0.0,0,0.0,52,0.838710,0,0.000000,62,-30.5,0,-61,-1891,387020.0

In [1]:
bureau_bal_final = agg_fn_numeric(temp.drop('SK_ID_BUREAU', axis = 1), 'SK_ID_CURR', 'AGG')
bureau_bal_final

NameError: name 'agg_fn_numeric' is not defined

In [105]:
def double_agg_fn(data, ids, names, id_df):
    agg_conti = agg_fn_numeric(data, ids[1], names[1])
    agg_cat = agg_fn_categorical(data, ids[1], names[1])
    agg_merged = agg_cat.merge(agg_conti, on = ids[1], how = 'outer')
    temp = agg_merged.merge(id_df[[ids[1], ids[0]]], how = 'left', on = ids[1])
    final = agg_fn_numeric(temp.drop(ids[1], axis = 1), ids[0], names[0])
    return final

In [107]:
double_agg_fn(bureau_bal, ['SK_ID_CURR', 'SK_ID_BUREAU'], ['AGG', 'BURAEU_BAL'], bureau)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,SK_ID_CURR,AGG_BURAEU_BAL_STATUS_0_COUNT_COUNT,AGG_BURAEU_BAL_STATUS_0_COUNT_MEAN,AGG_BURAEU_BAL_STATUS_0_COUNT_MAX,AGG_BURAEU_BAL_STATUS_0_COUNT_MIN,AGG_BURAEU_BAL_STATUS_0_COUNT_SUM,AGG_BURAEU_BAL_STATUS_0_COUNT_NORM_COUNT,AGG_BURAEU_BAL_STATUS_0_COUNT_NORM_MEAN,AGG_BURAEU_BAL_STATUS_0_COUNT_NORM_MAX,AGG_BURAEU_BAL_STATUS_0_COUNT_NORM_MIN,AGG_BURAEU_BAL_STATUS_0_COUNT_NORM_SUM,AGG_BURAEU_BAL_STATUS_1_COUNT_COUNT,AGG_BURAEU_BAL_STATUS_1_COUNT_MEAN,AGG_BURAEU_BAL_STATUS_1_COUNT_MAX,AGG_BURAEU_BAL_STATUS_1_COUNT_MIN,AGG_BURAEU_BAL_STATUS_1_COUNT_SUM,AGG_BURAEU_BAL_STATUS_1_COUNT_NORM_COUNT,AGG_BURAEU_BAL_STATUS_1_COUNT_NORM_MEAN,AGG_BURAEU_BAL_STATUS_1_COUNT_NORM_MAX,AGG_BURAEU_BAL_STATUS_1_COUNT_NORM_MIN,AGG_BURAEU_BAL_STATUS_1_COUNT_NORM_SUM,AGG_BURAEU_BAL_STATUS_2_COUNT_COUNT,AGG_BURAEU_BAL_STATUS_2_COUNT_MEAN,AGG_BURAEU_BAL_STATUS_2_COUNT_MAX,AGG_BURAEU_BAL_STATUS_2_COUNT_MIN,AGG_BURAEU_BAL_STATUS_2_COUNT_SUM,AGG_BURAEU_BAL_STATUS_2_COUNT_NORM_COUNT,AGG_BURAEU_BAL_STATUS_2_COUNT_NORM_MEAN,AGG_BURAEU_BAL_STATUS_2_COUNT_NORM_MAX,AGG_BURAEU_BAL_STATUS_2_COUNT_NORM_MIN,AGG_BURAEU_BAL_STATUS_2_COUNT_NORM_SUM,AGG_BURAEU_BAL_STATUS_3_COUNT_COUNT,AGG_BURAEU_BAL_STATUS_3_COUNT_MEAN,AGG_BURAEU_BAL_STATUS_3_COUNT_MAX,AGG_BURAEU_BAL_STATUS_3_COUNT_MIN,AGG_BURAEU_BAL_STATUS_3_COUNT_SUM,AGG_BURAEU_BAL_STATUS_3_COUNT_NORM_COUNT,AGG_BURAEU_BAL_STATUS_3_COUNT_NORM_MEAN,AGG_BURAEU_BAL_STATUS_3_COUNT_NORM_MAX,AGG_BURAEU_BAL_STATUS_3_COUNT_NORM_MIN,AGG_BURAEU_BAL_STATUS_3_COUNT_NORM_SUM,AGG_BURAEU_BAL_STATUS_4_COUNT_COUNT,AGG_BURAEU_BAL_STATUS_4_COUNT_MEAN,AGG_BURAEU_BAL_STATUS_4_COUNT_MAX,AGG_BURAEU_BAL_STATUS_4_COUNT_MIN,AGG_BURAEU_BAL_STATUS_4_COUNT_SUM,AGG_BURAEU_BAL_STATUS_4_COUNT_NORM_COUNT,AGG_BURAEU_BAL_STATUS_4_COUNT_NORM_MEAN,AGG_BURAEU_BAL_STATUS_4_COUNT_NORM_MAX,AGG_BURAEU_BAL_STATUS_4_COUNT_NORM_MIN,AGG_BURAEU_BAL_STATUS_4_COUNT_NORM_SUM,AGG_BURAEU_BAL_STATUS_5_COUNT_COUNT,AGG_BURAEU_BAL_STATUS_5_COUNT_MEAN,AGG_BURAEU_BAL_STATUS_5_COUNT_MAX,AGG_BURAEU_BAL_STATUS_5_COUNT_MIN,AGG_BURAEU_BAL_STATUS_5_COUNT_SUM,AGG_BURAEU_BAL_STATUS_5_COUNT_NORM_COUNT,AGG_BURAEU_BAL_STATUS_5_COUNT_NORM_MEAN,AGG_BURAEU_BAL_STATUS_5_COUNT_NORM_MAX,AGG_BURAEU_BAL_STATUS_5_COUNT_NORM_MIN,AGG_BURAEU_BAL_STATUS_5_COUNT_NORM_SUM,AGG_BURAEU_BAL_STATUS_C_COUNT_COUNT,AGG_BURAEU_BAL_STATUS_C_COUNT_MEAN,AGG_BURAEU_BAL_STATUS_C_COUNT_MAX,AGG_BURAEU_BAL_STATUS_C_COUNT_MIN,AGG_BURAEU_BAL_STATUS_C_COUNT_SUM,AGG_BURAEU_BAL_STATUS_C_COUNT_NORM_COUNT,AGG_BURAEU_BAL_STATUS_C_COUNT_NORM_MEAN,AGG_BURAEU_BAL_STATUS_C_COUNT_NORM_MAX,AGG_BURAEU_BAL_STATUS_C_COUNT_NORM_MIN,AGG_BURAEU_BAL_STATUS_C_COUNT_NORM_SUM,AGG_BURAEU_BAL_STATUS_X_COUNT_COUNT,AGG_BURAEU_BAL_STATUS_X_COUNT_MEAN,AGG_BURAEU_BAL_STATUS_X_COUNT_MAX,AGG_BURAEU_BAL_STATUS_X_COUNT_MIN,AGG_BURAEU_BAL_STATUS_X_COUNT_SUM,AGG_BURAEU_BAL_STATUS_X_COUNT_NORM_COUNT,AGG_BURAEU_BAL_STATUS_X_COUNT_NORM_MEAN,AGG_BURAEU_BAL_STATUS_X_COUNT_NORM_MAX,AGG_BURAEU_BAL_STATUS_X_COUNT_NORM_MIN,AGG_BURAEU_BAL_STATUS_X_COUNT_NORM_SUM,AGG_BURAEU_BAL_MONTHS_BALANCE_COUNT_COUNT,AGG_BURAEU_BAL_MONTHS_BALANCE_COUNT_MEAN,AGG_BURAEU_BAL_MONTHS_BALANCE_COUNT_MAX,AGG_BURAEU_BAL_MONTHS_BALANCE_COUNT_MIN,AGG_BURAEU_BAL_MONTHS_BALANCE_COUNT_SUM,AGG_BURAEU_BAL_MONTHS_BALANCE_MEAN_COUNT,AGG_BURAEU_BAL_MONTHS_BALANCE_MEAN_MEAN,AGG_BURAEU_BAL_MONTHS_BALANCE_MEAN_MAX,AGG_BURAEU_BAL_MONTHS_BALANCE_MEAN_MIN,AGG_BURAEU_BAL_MONTHS_BALANCE_MEAN_SUM,AGG_BURAEU_BAL_MONTHS_BALANCE_MAX_COUNT,AGG_BURAEU_BAL_MONTHS_BALANCE_MAX_MEAN,AGG_BURAEU_BAL_MONTHS_BALANCE_MAX_MAX,AGG_BURAEU_BAL_MONTHS_BALANCE_MAX_MIN,AGG_BURAEU_BAL_MONTHS_BALANCE_MAX_SUM,AGG_BURAEU_BAL_MONTHS_BALANCE_MIN_COUNT,AGG_BURAEU_BAL_MONTHS_BALANCE_MIN_MEAN,AGG_BURAEU_BAL_MONTHS_BALANCE_MIN_MAX,AGG_BURAEU_BAL_MONTHS_BALANCE_MIN_MIN,AGG_BURAEU_BAL_MONTHS_BALANCE_MIN_SUM,AGG_BURAEU_BAL_MONTHS_BALANCE_SUM_COUNT,AGG_BURAEU_BAL_MONTHS_BALANCE_SUM_MEAN,AGG_BURAEU_BAL_MONTHS_BALANCE_SUM_MAX,AGG_BURAEU_BAL_MONTHS_BALANCE_SUM_MIN,AGG_BURAEU_BAL_MONTHS_BALANCE_SUM_SUM
0,100001.0,7,4.428571,12,1,31.0,7,0.336651,1.000000,0.019231,2.356557,7,0.142857,1,0,1,7,0.007519,0.052632,0.0,0.052632,7,0.0,0,0,0,7,0.0,0.0,0.0,0.0,7,0.0,0,0,0,7,0.0,0.0,0.0,0.0,7,0.0,0,0,0,7,0.0,0.0,0.0,0.0,7,0.0,0,0,0.0,7,0.0,0.0,0.0,0.0,7,15.714286,44,0,110.0,7,0.441240,0.966667,0.000000,3.088683,7,4.285714,9,0,30.0,7,0.214590,0.500000,0.000000,1.502129,7,24.571429,52,2,172,7,-11.785714,-0.5,-25.5,-82.5,7,0.000000,0,0,0,7,-23.571429,-1,-51,-165,7,-400.000000,-1,-1326,-2800
1,100002.0,8,5.625000,18,2,45.0,8,0.406960,0.818182,0.187500,3.255682,8,3.375000,6,0,27,8,0.255682,0.500000,0.0,2.045455,8,0.0,0,0,0,8,0.0,0.0,0.0,0.0,8,0.0,0,0,0,8,0.0,0.0,0.0,0.0,8,0.0,0,0,0,8,0.0,0.0,0.0,0.0,8,0.0,0,0,0.0,8,0.0,0.0,0.0,0.0,8,2.875000,13,0,23.0,8,0.175426,0.812500,0.000000,1.403409,8,1.875000,3,0,15.0,8,0.161932,0.500000,0.000000,1.295455,8,13.750000,22,4,110,8,-21.875000,-1.5,-39.5,-175.0,8,-15.500000,0,-32,-124,8,-28.250000,-3,-47,-226,8,-337.625000,-6,-632,-2701
2,100005.0,3,4.666667,7,2,14.0,3,0.735043,1.000000,0.538462,2.205128,3,0.000000,0,0,0,3,0.000000,0.000000,0.0,0.000000,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0.0,3,0.0,0.0,0.0,0.0,3,1.666667,5,0,5.0,3,0.128205,0.384615,0.000000,0.384615,3,0.666667,1,0,2.0,3,0.136752,0.333333,0.000000,0.410256,3,7.000000,13,3,21,3,-3.000000,-1.0,-6.0,-9.0,3,0.000000,0,0,0,3,-6.000000,-2,-12,-18,3,-30.333333,-3,-78,-91
3,100010.0,2,10.000000,10,10,20.0,2,0.277778,0.277778,0.277778,0.555556,2,0.000000,0,0,0,2,0.000000,0.000000,0.0,0.000000,2,0.0,0,0,0,2,0.0,0.0,0.0,0.0,2,0.0,0,0,0,2,0.0,0.0,0.0,0.0,2,0.0,0,0,0,2,0.0,0.0,0.0,0.0,2,0.0,0,0,0.0,2,0.0,0.0,0.0,0.0,2,26.000000,26,26,52.0,2,0.722222,0.722222,0.722222,1.444444,2,0.000000,0,0,0.0,2,0.000000,0.000000,0.000000,0.000000,2,36.000000,36,36,72,2,-46.000000,-19.5,-72.5,-92.0,2,-28.500000,-2,-55,-57,2,-63.500000,-37,-90,-127,2,-1656.000000,-702,-2610,-3312
4,100013.0,4,19.750000,34,0,79.0,4,0.320718,0.618182,0.000000,1.282872,4,1.750000,3,0,7,4,0.027701,0.045455,0.0,0.110804,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0.0,4,0.0,0.0,0.0,0.0,4,25.750000,44,0,103.0,4,0.397036,0.666667,0.000000,1.588142,4,10.250000,40,0,41.0,4,0.254545,1.000000,0.000000,1.018182,4,57.500000,69,40,230,4,-28.250000,-19.5,-34.0,-113.0,4,0.000000,0,0,0,4,-56.500000,-39,-68,-226,4,-1689.000000,-780,-2346,-6756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134537,456247.0,11,6.000000,9,1,66.0,11,0.325528,0.750000,0.034483,3.580808,11,0.000000,0,0,0,11,0.000000,0.000000,0.0,0.000000,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0.0,11,0.0,0.0,0.0,0.0,11,19.909091,72,0,219.0,11,0.505634,0.965517,0.000000,5.561970,11,3.181818,5,0,35.0,11,0.168838,0.500000,0.000000,1.857222,11,29.090909,82,10,320,11,-19.863636,-4.5,-53.0,-218.5,11,-5.818182,0,-40,-64,11,-33.909091,-9,-81,-373,11,-793.636364,-45,-3321,-8730
134538,456250.0,3,4.000000,8,2,12.0,3,0.130259,0.242424,0.071429,0.390776,3,0.000000,0,0,0,3,0.000000,0.000000,0.0,0.000000,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0.0,3,0.0,0.0,0.0,0.0,3,8.333333,25,0,25.0,3,0.252525,0.757576,0.000000,0.757576,3,16.666667,26,0,50.0,3,0.617216,0.928571,0.000000,1.851648,3,29.000000,33,26,87,3,-14.000000,-12.5,-16.0,-42.0,3,0.000000,0,0,0,3,-28.000000,-25,-32,-84,3,-410.333333,-325,-528,-1231
134539,456253.0,4,11.750000,12,11,47.0,4,0.404906,0.458333,0.387097,1.619624,4,0.000000,0,0,0,4,0.000000,0.000000,0.0,0.000000,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0.0,4,0.0,0.0,0.0,0.0,4,14.250000,19,0,57.0,4,0.459677,0.612903,0.000000,1.838710,4,3.250000,13,0,13.0,4,0.135417,0.541667,0.000000,0.541667,4,29.250000,31,24,117,4,-14.125000,-11.5,-15.0,-56.5,4,0.000000,0,0,0,4,-28.250000,-23,-30,-113,4,-417.750000,-276,-465,-1671
134540,456254.0,1,8.000000,8,8,8.0,1,0.216216,0.216216,0.216216,0.216216,1,0.000000,0,0,0,1,0.000000,0.000000,0.0,0.000000,1,0.0,0,0,0,1,0.0,0.0,0.0,0.0,1,0.0,0,0,0,1,0.0,0.0,0.0,0.0,1,0.0,0,0,0,1,0.0,0.0,0.0,0.0,1,0.0,0,0,0.0,1,0.0,0.0,0.0,0.0,1,29.000000,29,29,29.0,1,0.783784,0.783784,0.783784,0.783784,1,0.000000,0,0,0.0,1,0.000000,0.000000,0.000000,0.000000,1,37.000000,37,37,37,1,-18.000000,-18.0,-18.0,-18.0,1,0.000000,0,0,0,1,-36.000000,-36,-36,-36,1,-666.000000,-666,-666,-666
134541,456255.0,11,5.727273,9,1,63.0,11,0.283249,0.692308,0.028571,3.115737,11,0.000000,0,0,0,11,0.000000,0.000000,0.0,0.000000,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0.0,11,0.0,0.0,0.0,0.0,11,19.363636,33,3,213.0,11,0.645601,0.942857,0.230769,7.101613,11,1.545455,2,1,17.0,11,0.071150,0.166667,0.028571,0.782649,11,26.636364,35,12,293,11,-22.272727,-5.5,-60.0,-245.0,11,-9.454545,0,-44,-104,11,-35.090909,-11,-76,-386,11,-703.000000,-66,-2065,-7733

In [108]:
bureau_bal_final

,SK_ID_CURR,AGG_BUREAU_BAL_STATUS_0_COUNT_COUNT,AGG_BUREAU_BAL_STATUS_0_COUNT_MEAN,AGG_BUREAU_BAL_STATUS_0_COUNT_MAX,AGG_BUREAU_BAL_STATUS_0_COUNT_MIN,AGG_BUREAU_BAL_STATUS_0_COUNT_SUM,AGG_BUREAU_BAL_STATUS_0_COUNT_NORM_COUNT,AGG_BUREAU_BAL_STATUS_0_COUNT_NORM_MEAN,AGG_BUREAU_BAL_STATUS_0_COUNT_NORM_MAX,AGG_BUREAU_BAL_STATUS_0_COUNT_NORM_MIN,AGG_BUREAU_BAL_STATUS_0_COUNT_NORM_SUM,AGG_BUREAU_BAL_STATUS_1_COUNT_COUNT,AGG_BUREAU_BAL_STATUS_1_COUNT_MEAN,AGG_BUREAU_BAL_STATUS_1_COUNT_MAX,AGG_BUREAU_BAL_STATUS_1_COUNT_MIN,AGG_BUREAU_BAL_STATUS_1_COUNT_SUM,AGG_BUREAU_BAL_STATUS_1_COUNT_NORM_COUNT,AGG_BUREAU_BAL_STATUS_1_COUNT_NORM_MEAN,AGG_BUREAU_BAL_STATUS_1_COUNT_NORM_MAX,AGG_BUREAU_BAL_STATUS_1_COUNT_NORM_MIN,AGG_BUREAU_BAL_STATUS_1_COUNT_NORM_SUM,AGG_BUREAU_BAL_STATUS_2_COUNT_COUNT,AGG_BUREAU_BAL_STATUS_2_COUNT_MEAN,AGG_BUREAU_BAL_STATUS_2_COUNT_MAX,AGG_BUREAU_BAL_STATUS_2_COUNT_MIN,AGG_BUREAU_BAL_STATUS_2_COUNT_SUM,AGG_BUREAU_BAL_STATUS_2_COUNT_NORM_COUNT,AGG_BUREAU_BAL_STATUS_2_COUNT_NORM_MEAN,AGG_BUREAU_BAL_STATUS_2_COUNT_NORM_MAX,AGG_BUREAU_BAL_STATUS_2_COUNT_NORM_MIN,AGG_BUREAU_BAL_STATUS_2_COUNT_NORM_SUM,AGG_BUREAU_BAL_STATUS_3_COUNT_COUNT,AGG_BUREAU_BAL_STATUS_3_COUNT_MEAN,AGG_BUREAU_BAL_STATUS_3_COUNT_MAX,AGG_BUREAU_BAL_STATUS_3_COUNT_MIN,AGG_BUREAU_BAL_STATUS_3_COUNT_SUM,AGG_BUREAU_BAL_STATUS_3_COUNT_NORM_COUNT,AGG_BUREAU_BAL_STATUS_3_COUNT_NORM_MEAN,AGG_BUREAU_BAL_STATUS_3_COUNT_NORM_MAX,AGG_BUREAU_BAL_STATUS_3_COUNT_NORM_MIN,AGG_BUREAU_BAL_STATUS_3_COUNT_NORM_SUM,AGG_BUREAU_BAL_STATUS_4_COUNT_COUNT,AGG_BUREAU_BAL_STATUS_4_COUNT_MEAN,AGG_BUREAU_BAL_STATUS_4_COUNT_MAX,AGG_BUREAU_BAL_STATUS_4_COUNT_MIN,AGG_BUREAU_BAL_STATUS_4_COUNT_SUM,AGG_BUREAU_BAL_STATUS_4_COUNT_NORM_COUNT,AGG_BUREAU_BAL_STATUS_4_COUNT_NORM_MEAN,AGG_BUREAU_BAL_STATUS_4_COUNT_NORM_MAX,AGG_BUREAU_BAL_STATUS_4_COUNT_NORM_MIN,AGG_BUREAU_BAL_STATUS_4_COUNT_NORM_SUM,AGG_BUREAU_BAL_STATUS_5_COUNT_COUNT,AGG_BUREAU_BAL_STATUS_5_COUNT_MEAN,AGG_BUREAU_BAL_STATUS_5_COUNT_MAX,AGG_BUREAU_BAL_STATUS_5_COUNT_MIN,AGG_BUREAU_BAL_STATUS_5_COUNT_SUM,AGG_BUREAU_BAL_STATUS_5_COUNT_NORM_COUNT,AGG_BUREAU_BAL_STATUS_5_COUNT_NORM_MEAN,AGG_BUREAU_BAL_STATUS_5_COUNT_NORM_MAX,AGG_BUREAU_BAL_STATUS_5_COUNT_NORM_MIN,AGG_BUREAU_BAL_STATUS_5_COUNT_NORM_SUM,AGG_BUREAU_BAL_STATUS_C_COUNT_COUNT,AGG_BUREAU_BAL_STATUS_C_COUNT_MEAN,AGG_BUREAU_BAL_STATUS_C_COUNT_MAX,AGG_BUREAU_BAL_STATUS_C_COUNT_MIN,AGG_BUREAU_BAL_STATUS_C_COUNT_SUM,AGG_BUREAU_BAL_STATUS_C_COUNT_NORM_COUNT,AGG_BUREAU_BAL_STATUS_C_COUNT_NORM_MEAN,AGG_BUREAU_BAL_STATUS_C_COUNT_NORM_MAX,AGG_BUREAU_BAL_STATUS_C_COUNT_NORM_MIN,AGG_BUREAU_BAL_STATUS_C_COUNT_NORM_SUM,AGG_BUREAU_BAL_STATUS_X_COUNT_COUNT,AGG_BUREAU_BAL_STATUS_X_COUNT_MEAN,AGG_BUREAU_BAL_STATUS_X_COUNT_MAX,AGG_BUREAU_BAL_STATUS_X_COUNT_MIN,AGG_BUREAU_BAL_STATUS_X_COUNT_SUM,AGG_BUREAU_BAL_STATUS_X_COUNT_NORM_COUNT,AGG_BUREAU_BAL_STATUS_X_COUNT_NORM_MEAN,AGG_BUREAU_BAL_STATUS_X_COUNT_NORM_MAX,AGG_BUREAU_BAL_STATUS_X_COUNT_NORM_MIN,AGG_BUREAU_BAL_STATUS_X_COUNT_NORM_SUM,AGG_BUREAU_BAL_MONTHS_BALANCE_COUNT_COUNT,AGG_BUREAU_BAL_MONTHS_BALANCE_COUNT_MEAN,AGG_BUREAU_BAL_MONTHS_BALANCE_COUNT_MAX,AGG_BUREAU_BAL_MONTHS_BALANCE_COUNT_MIN,AGG_BUREAU_BAL_MONTHS_BALANCE_COUNT_SUM,AGG_BUREAU_BAL_MONTHS_BALANCE_MEAN_COUNT,AGG_BUREAU_BAL_MONTHS_BALANCE_MEAN_MEAN,AGG_BUREAU_BAL_MONTHS_BALANCE_MEAN_MAX,AGG_BUREAU_BAL_MONTHS_BALANCE_MEAN_MIN,AGG_BUREAU_BAL_MONTHS_BALANCE_MEAN_SUM,AGG_BUREAU_BAL_MONTHS_BALANCE_MAX_COUNT,AGG_BUREAU_BAL_MONTHS_BALANCE_MAX_MEAN,AGG_BUREAU_BAL_MONTHS_BALANCE_MAX_MAX,AGG_BUREAU_BAL_MONTHS_BALANCE_MAX_MIN,AGG_BUREAU_BAL_MONTHS_BALANCE_MAX_SUM,AGG_BUREAU_BAL_MONTHS_BALANCE_MIN_COUNT,AGG_BUREAU_BAL_MONTHS_BALANCE_MIN_MEAN,AGG_BUREAU_BAL_MONTHS_BALANCE_MIN_MAX,AGG_BUREAU_BAL_MONTHS_BALANCE_MIN_MIN,AGG_BUREAU_BAL_MONTHS_BALANCE_MIN_SUM,AGG_BUREAU_BAL_MONTHS_BALANCE_SUM_COUNT,AGG_BUREAU_BAL_MONTHS_BALANCE_SUM_MEAN,AGG_BUREAU_BAL_MONTHS_BALANCE_SUM_MAX,AGG_BUREAU_BAL_MONTHS_BALANCE_SUM_MIN,AGG_BUREAU_BAL_MONTHS_BALANCE_SUM_SUM
0,100001.0,7,4.428571,12,1,31.0,7,0.336651,1.000000,0.019231,2.356557,7,0.142857,1,0,1,7,0.007519,0.052632,0.0,0.052632,7,0.0,0,0,0,7,0.0,0.0,0.0,0.0,7,0.0,0,0,0,7,0.0,0.0,0.0,0.0,7,0.0,0,0,0,7,0.0,0.0,0.0,0.0,7,0.0,0,0,0.0,7,0.0,0.0,0.0,0.0,7,15.714286,44,0,110.0,7,0.441240,0.966667,0.000000,3.088683,7,4.285714,9,0,30.0,7,0.214590,0.500000,0.000000,1.502129,7,24.571429,52,2,172,7,-11.785714,-0.5,-25.5,-82.5,7,0.000000,0,0,0,7,-23.571429,-1,-51,-165,7,-400.000000,-1,-1326,-2800
1,100002.0,8,5.625000,18,2,45.0,8,0.406960,0.818182,0.187500,3.255682,8,3.375000,6,0,27,8,0.255682,0.500000,0.0,2.045455,8,0.0,0,0,0,8,0.0,0.0,0.0,0.0,8,0.0,0,0,0,8,0.0,0.0,0.0,0.0,8,0.0,0,0,0,8,0.0,0.0,0.0,0.0,8,0.0,0,0,0.0,8,0.0,0.0,0.0,0.0,8,2.875000,13,0,23.0,8,0.175426,0.812500,0.000000,1.403409,8,1.875000,3,0,15.0,8,0.161932,0.500000,0.000000,1.295455,8,13.750000,22,4,110,8,-21.875000,-1.5,-39.5,-175.0,8,-15.500000,0,-32,-124,8,-28.250000,-3,-47,-226,8,-337.625000,-6,-632,-2701
2,100005.0,3,4.666667,7,2,14.0,3,0.735043,1.000000,0.538462,2.205128,3,0.000000,0,0,0,3,0.000000,0.000000,0.0,0.000000,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0.0,3,0.0,0.0,0.0,0.0,3,1.666667,5,0,5.0,3,0.128205,0.384615,0.000000,0.384615,3,0.666667,1,0,2.0,3,0.136752,0.333333,0.000000,0.410256,3,7.000000,13,3,21,3,-3.000000,-1.0,-6.0,-9.0,3,0.000000,0,0,0,3,-6.000000,-2,-12,-18,3,-30.333333,-3,-78,-91
3,100010.0,2,10.000000,10,10,20.0,2,0.277778,0.277778,0.277778,0.555556,2,0.000000,0,0,0,2,0.000000,0.000000,0.0,0.000000,2,0.0,0,0,0,2,0.0,0.0,0.0,0.0,2,0.0,0,0,0,2,0.0,0.0,0.0,0.0,2,0.0,0,0,0,2,0.0,0.0,0.0,0.0,2,0.0,0,0,0.0,2,0.0,0.0,0.0,0.0,2,26.000000,26,26,52.0,2,0.722222,0.722222,0.722222,1.444444,2,0.000000,0,0,0.0,2,0.000000,0.000000,0.000000,0.000000,2,36.000000,36,36,72,2,-46.000000,-19.5,-72.5,-92.0,2,-28.500000,-2,-55,-57,2,-63.500000,-37,-90,-127,2,-1656.000000,-702,-2610,-3312
4,100013.0,4,19.750000,34,0,79.0,4,0.320718,0.618182,0.000000,1.282872,4,1.750000,3,0,7,4,0.027701,0.045455,0.0,0.110804,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0.0,4,0.0,0.0,0.0,0.0,4,25.750000,44,0,103.0,4,0.397036,0.666667,0.000000,1.588142,4,10.250000,40,0,41.0,4,0.254545,1.000000,0.000000,1.018182,4,57.500000,69,40,230,4,-28.250000,-19.5,-34.0,-113.0,4,0.000000,0,0,0,4,-56.500000,-39,-68,-226,4,-1689.000000,-780,-2346,-6756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134537,456247.0,11,6.000000,9,1,66.0,11,0.325528,0.750000,0.034483,3.580808,11,0.000000,0,0,0,11,0.000000,0.000000,0.0,0.000000,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0.0,11,0.0,0.0,0.0,0.0,11,19.909091,72,0,219.0,11,0.505634,0.965517,0.000000,5.561970,11,3.181818,5,0,35.0,11,0.168838,0.500000,0.000000,1.857222,11,29.090909,82,10,320,11,-19.863636,-4.5,-53.0,-218.5,11,-5.818182,0,-40,-64,11,-33.909091,-9,-81,-373,11,-793.636364,-45,-3321,-8730
134538,456250.0,3,4.000000,8,2,12.0,3,0.130259,0.242424,0.071429,0.390776,3,0.000000,0,0,0,3,0.000000,0.000000,0.0,0.000000,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0,3,0.0,0.0,0.0,0.0,3,0.0,0,0,0.0,3,0.0,0.0,0.0,0.0,3,8.333333,25,0,25.0,3,0.252525,0.757576,0.000000,0.757576,3,16.666667,26,0,50.0,3,0.617216,0.928571,0.000000,1.851648,3,29.000000,33,26,87,3,-14.000000,-12.5,-16.0,-42.0,3,0.000000,0,0,0,3,-28.000000,-25,-32,-84,3,-410.333333,-325,-528,-1231
134539,456253.0,4,11.750000,12,11,47.0,4,0.404906,0.458333,0.387097,1.619624,4,0.000000,0,0,0,4,0.000000,0.000000,0.0,0.000000,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0,4,0.0,0.0,0.0,0.0,4,0.0,0,0,0.0,4,0.0,0.0,0.0,0.0,4,14.250000,19,0,57.0,4,0.459677,0.612903,0.000000,1.838710,4,3.250000,13,0,13.0,4,0.135417,0.541667,0.000000,0.541667,4,29.250000,31,24,117,4,-14.125000,-11.5,-15.0,-56.5,4,0.000000,0,0,0,4,-28.250000,-23,-30,-113,4,-417.750000,-276,-465,-1671
134540,456254.0,1,8.000000,8,8,8.0,1,0.216216,0.216216,0.216216,0.216216,1,0.000000,0,0,0,1,0.000000,0.000000,0.0,0.000000,1,0.0,0,0,0,1,0.0,0.0,0.0,0.0,1,0.0,0,0,0,1,0.0,0.0,0.0,0.0,1,0.0,0,0,0,1,0.0,0.0,0.0,0.0,1,0.0,0,0,0.0,1,0.0,0.0,0.0,0.0,1,29.000000,29,29,29.0,1,0.783784,0.783784,0.783784,0.783784,1,0.000000,0,0,0.0,1,0.000000,0.000000,0.000000,0.000000,1,37.000000,37,37,37,1,-18.000000,-18.0,-18.0,-18.0,1,0.000000,0,0,0,1,-36.000000,-36,-36,-36,1,-666.000000,-666,-666,-666
134541,456255.0,11,5.727273,9,1,63.0,11,0.283249,0.692308,0.028571,3.115737,11,0.000000,0,0,0,11,0.000000,0.000000,0.0,0.000000,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0,11,0.0,0.0,0.0,0.0,11,0.0,0,0,0.0,11,0.0,0.0,0.0,0.0,11,19.363636,33,3,213.0,11,0.645601,0.942857,0.230769,7.101613,11,1.545455,2,1,17.0,11,0.071150,0.166667,0.028571,0.782649,11,26.636364,35,12,293,11,-22.272727,-5.5,-60.0,-245.0,11,-9.454545,0,-44,-104,11,-35.090909,-11,-76,-386,11,-703.000000,-66,-2065,-7733

In [110]:
pos_cash = pd.read_csv('../input/home-credit-default-risk/POS_CASH_balance.csv')

In [111]:
pos_cash

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0
...,...,...,...,...,...,...,...,...
10001353,2448283,226558,-20,6.0,0.0,Active,843,0
10001354,1717234,141565,-19,12.0,0.0,Active,602,0
10001355,1283126,315695,-21,10.0,0.0,Active,609,0
10001356,1082516,450255,-22,12.0,0.0,Active,614,0
10001357,1259607,174278,-52,16.0,0.0,Completed,0,0

In [ ]:
double_agg_fn(pos_cash, ['SK_ID_CURR', 'SK_ID_PREV'], ['AGG', 'POS_CASH_BAL'], pos_cash)